### PR TITLE
Activity page

### PR DESCRIPTION
**Pull request by vbhv**
Master Task
https://github.com/ushahidi/platform/issues/436

Things to test-
1. Navigate to activity view
2. 'This Week' should be selected as the default period for the page
3. You should see data visualised in three visualisations/charts in this view - a line chart showing number of posts over time, a bar chart showing number of posts by categories, and a map showing posts
4. Check if the data shown is indeed for the selected time frame. The time frames that you can select are **This Week, This Month, All Time** (is data being shown consistent with the selected view?)
5. Check if charts labels make sense. Check for typos and illegibility when there is too much data being shown.
6. You should see upto 10 updates in the activity timeline aside component. Right now updates are only for new posts.

Notes:
~~1. There are no indicators for when data is loading or missing. You might just see blank charts for a few seconds while the data is loading. This is a TODO.~~
~~2. The recent activity timeline on right in non-functioning atm. This is a TODO~~
3. Charts showing most active posts and most active users is a pending item because it requires new API end points.
4. 'Today' time period is currently unavailable. Need to look into producing stats by the hour for this time range to be meaningful.

[Review on Reviewable](https://reviewable.io/reviews/ushahidi/platform-client/12)

### CODE REVIEW

**Comment by rjmackay** [comment]
I'd like to split it out more into directives/services.. but we've got several iterations of this to go. Cleaning up now would probably be premature. 

---

Reviewed 13 of 16 files at r1.
Review status: 13 of 16 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[app/activity/activity-module.js, line 5 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/12#-JzxLDo5lkZZkcQvsI0D)** ([raw file](https://github.com/ushahidi/platform-client/blob/fb3f75fc1d538aa7cc666723a2752d77a7229bb9/app/activity/activity-module.js#L5)):</sup>
This shouldn't be here..

---

<sup>**[app/activity/controllers/activity-controller.js, line 93 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/12#-JzxMRc3CtDzcRyG9IrU)** ([raw file](https://github.com/ushahidi/platform-client/blob/fb3f75fc1d538aa7cc666723a2752d77a7229bb9/app/activity/controllers/activity-controller.js#L93)):</sup>
did you figure out a solution for this at all?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ushahidi/platform-client/12)

**Comment by vbhv** [comment]
Yes, i created a generic chart directive and a directive for the aside timeline for now.

---

Review status: 13 of 16 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[app/activity/activity-module.js, line 5 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/12#-JzxLDo5lkZZkcQvsI0D)** ([raw file](https://github.com/ushahidi/platform-client/blob/fb3f75fc1d538aa7cc666723a2752d77a7229bb9/app/activity/activity-module.js#L5)):</sup>
Will remove that.

---

<sup>**[app/activity/controllers/activity-controller.js, line 93 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/12#-JzxMRc3CtDzcRyG9IrU)** ([raw file](https://github.com/ushahidi/platform-client/blob/fb3f75fc1d538aa7cc666723a2752d77a7229bb9/app/activity/controllers/activity-controller.js#L93)):</sup>
Yes on line 152 I get the start date from the first post returned when 'All' period is selected. I should remove this comment to not mislead. its solved for now.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ushahidi/platform-client/12)

**Comment by rjmackay** [comment]
@vbhv test failures -> https://www.dropbox.com/s/s7umr3pxyngrk60/Screenshot%202015-09-28%2010.17.15.png?dl=0

https://travis-ci.org/ushahidi/platform-client/builds/82287046
I think they're just coding style issues mostly but they need to be fixed to land.

**Comment by vbhv** [comment]
Yes there actually are remaining styling issues but they are from a file I didn't touch. So I left them alone. Will look.

**Pull request merged**
