### PR TITLE
#4115 Checkboxes within mode-context filters are visible when receive focus

### PR DESCRIPTION
**Pull request by siggrid**
This pull request makes the following changes:

Makes checkbox in mode-context visible, when checkbox receives keyboard focus:
- Checks if top-level parent element has focused checkbox inside and adds to `<div class="survey-filter-label">` element class `"child-focused"`, which contains proper styles
- Prevents re-rendering html within Datasource filters form - so focus doesn’t get lost when checking/unchecking the checkbox.

This PR requires PR in Platform-pattern-library to work properly
https://github.com/ushahidi/platform-pattern-library/pull/252

Testing checklist:
- [ ] go to Map page
- [ ] use Tab key to navigate within the page
- [ ] checkbox within mode-context filters is visible when receives focus
- [ ] checkbox stays focused when checking/unchecking it with Space key
- [ ] checkbox hides when press Tab key
- [ ] next checkbox is focused and visible

- [x] I certify that I ran my checklist

survey-new

Fixes ushahidi/platform# .

Ping @ushahidi/platform

### CODE REVIEW

**Review by rowasc — APPROVED** [review]
LGTM . @Angamanga would you be able to take a look at the PL (and of course if you have more ideas for this PR lmk)

**Review by rowasc — APPROVED** [review]
pre-approving since we're close to the approval deadlines I think and this looks good to me. 
Walter: please do not merge until the pattern library is approved too (linked in the description)

**Comment by siggrid** [comment]
Thanks @rowasc 
Sorry, just noticed that I dismissed your previous review, when I was trying to update my fork.

**Comment by Angamanga** [comment]
@siggrid Sorry for the delay in review/reply! I have reviewed the pattern-library and it is approved.
@rowasc @Obadha2 We need to wait with merging this until I have a new Pattern-library release out, i'll ping you when its ready.

**Comment by Angamanga** [comment]
@Obadha2 The changes for the PL is in this PR: https://github.com/ushahidi/platform-client/pull/1624

**Comment by Obadha2** [comment]
QA'd, passes. 👍

**Pull request merged**
