### PR TITLE
Added alert role to alerts to improve accessibility

### PR DESCRIPTION
**Pull request by stacytonui**
This pull request makes the following changes:
-Added alert role to alerts to improve acccessibility

Testing checklist:

- [x] All the alerts have the alert role added to them and still function as alerts

- [x] I certify that I ran my checklist

Fixes ushahidi/platform#4109

Ping @ushahidi/platform

### CODE REVIEW

**Comment by stacytonui** [comment]
[clabot:check]

**Review by rowasc — CHANGES_REQUESTED** [review]
Hey @stacytonui thanks for your contribution!. Please add a testing checklist as directed by the PR template, and verify that it passes. 

Here's an example of a pull request with a checklist https://github.com/ushahidi/platform-client/pull/1542 
Thanks!

**Comment by stacytonui** [comment]
@rowasc Thankyou. I've added the checklist.

**Review by rowasc — CHANGES_REQUESTED** [review]
Hi @stacytonui , thanks for the change. 

- I hadn't noticed before, but I see role is in many cases being applied to field containers (ie divs for a field) withins alerts, not necessarily to the alert container itself. This happens in multiple files in this PR. It can quickly become really confusing if every element within a form is an alert. 

- related to the above: we should be using `alertdialog` role for interactive alerts (those which have forms) https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alertdialog_role . 

- related to the above: we should be using `alert` role for non-interactive alerts (those which are text-only) https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role. 


- In terms of testing checklist, it's important to detail what was tested. ie: Registration modal opens , Login , etc
cc @renujain31 copying you since it's one of the issues you created and maybe you have thoughts on the above that can help. I suspect that ticket may be focused on text-only alerts but accidentally ended up applied to forms in modals too

**Comment by stacytonui** [comment]
@rowasc oh right, apologies. I'll go through the linked articles and apply changes accordingly. Thanks for the correction

**Comment by Angamanga** [comment]
@stacytonui Do you plan to fix the requested changes for this pr? Otherwise I'll merge it into its own branch so someone else can continue 👍

**Comment by stacytonui** [comment]
Hey @Angamanga sorry for the late reply. Could you please assign this to someone else

**Pull request closed without merging**
