### PR TITLE
Allow links to be used in survey title

### PR DESCRIPTION
**Pull request by renujain31**
This pull request makes the following changes:
- Links in title is now rendered as links not texts.

Testing checklist:
- [ ] Create a new survey and add a link in the title field.
- [ ] Create a new post in that survey and see the survey title
- [ ] The link in the title would be clickable.

- [x] I certify that I ran my checklist

Fixes ushahidi/platform#3611 .

Ping @ushahidi/platform

### CODE REVIEW

**Review by rowasc — APPROVED** [review]
awesome. I'm assuming there's a PL change coming too :D thank you so much

**Comment by renujain31** [comment]
Hey @rowasc , Thanks for approving it. And I already have one PR for the PL change. Here https://github.com/ushahidi/platform-pattern-library/pull/253

**Comment by rowasc** [comment]
FYI @Angamanga @Obadha2 Initially we are just going for a `linkify` link style without markdown because I didn't want to pile complexity of another renderer... I'd probably like to later add a way to make it markdown (with-just-links) just so people can wrap their URLs with useful text and format them instead of throwing in bare links (that are now clickable thanks to linkify)

**Comment by Obadha2** [comment]
Passes QA. 👍

**Comment by Obadha2** [comment]
Just a note: This should be Survey Name and not Survey Title. That threw me off for a while.

**Pull request merged**
