### PR TITLE
issue #1858 positioning submit btn

### PR DESCRIPTION
**Pull request by Sunairaa**
This pull request makes the following changes:

- Position submit button at the end of the long submission page same as shown in the header. 
- Added HTML code for the submit and share button on app/main/posts/modify/post-editor.html

**Before**
image

**After**
image

**Note:** This issue also need to make scss code changes in platform-pattern-library so here I created PR for that refer link: https://github.com/ushahidi/platform-pattern-library/pull/251
 
Testing checklist:
- [ ] Got to /posts/create/1

- [ ] Click on + icon button.

- [ ] Submit and share button of long submission.

- [ ] I certify that I ran my checklist

Fixes ushahidi/platform#1858 .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by Sunairaa** [comment]
Hey @Angamanga can you review my work? 
Thanks!

**Comment by Sunairaa** [comment]
Hey @Angamanga can you review my work? 
Thanks!

**Review by Angamanga — CHANGES_REQUESTED** [review]
This works fine but I would like to move the css to the template "layout-a" instead. This change is specific to that view.

**Comment by Angamanga** [comment]
@Sunairaa Got confused by the two prs, the change in the above comment is meant to be in the PR in the pattern-library: https://github.com/ushahidi/platform-pattern-library/pull/251

**Comment by Sunairaa** [comment]
Hey @Angamanga can review my PR again? ushahidi/platform-pattern-library#251

**Review by Angamanga — APPROVED** [review]
Approved! Thank you for your contribution

**Comment by Sunairaa** [comment]
Thankyouu @Angamanga

**Comment by Sunairaa** [comment]
> Approved! Thank you for your contribution

@Angamanga you're welcome.. would love to contribute more!

**Comment by Angamanga** [comment]
@Obadha2 Ready for QA, needs this pr for styles: https://github.com/ushahidi/platform-client/pull/1626

**Comment by Obadha2** [comment]
QA'd, passes. 👍

**Pull request merged**
