### PR TITLE
Fix: Problems loading SVG on Safari (desktop & iOS) and Chrome (iOS) platform

### PR DESCRIPTION
**Pull request by Ifycode**
#### This pull request makes the following changes
- Fixes ushahidi/platform#4440

#### Testing checklist
- [x] All svgs load on safari and other browsers
- [x] I certify that I ran my checklist

Ping @ushahidi/platform

### CODE REVIEW

**Comment by Ifycode** [comment]
@tuxpiper please help review when you are free.

**Comment by tuxpiper** [comment]
@tuxpiper : deploy it so it can be tested . @webong  then can test / review

**Comment by webong** [comment]
image

@Ifycode few things I noted
1. The filter icon doesn't show, you might want to check that out.
2. The share button doesn't work again on mobile.

**Comment by Ifycode** [comment]
Hmm... Ok, thank you @webong I will look into it.

I also found one issue myself. So if you go to any other view apart from map, and then reload the page, looks like the sprite pushes down the posts or something. This doesn't happen on the map view.

**Comment by Ifycode** [comment]
I've fixed the issues now @tuxpiper @webong, please help review.

**Review by tuxpiper — APPROVED** [review]
Thank you @Ifycode and @webong  for your work and eye to detail.

@AmTryingMyBest this is ready for QA now

**Comment by AmTryingMyBest** [comment]
@Ifycode @webong I still don't have icons on Safari (note the left side menu) 
Screen Shot 2022-08-08 at 10 11 35 AM

**Comment by webong** [comment]
@AmTryingMyBest did you try clearing the browser cache and reloading the web page?

**Comment by AmTryingMyBest** [comment]
QA'd, passes. 👍

**Pull request merged**
