### PR TITLE
Newly created surveys are now visible in the import list

### PR DESCRIPTION
**Pull request by emmanuelhashy**
This pull request makes the following changes:
-

Testing checklist:
- Go to settings->surveys
- Create a new survey
- Save and go to settings->import
- Click on the "Import to survey"-dropdown
- The new survey is now on the list

- [ ] I certify that I ran my checklist

Fixes ushahidi/platform#4231 .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by emmanuelhashy** [comment]
@Angamanga I have finished the task. Kindly review. Thanks!

**Review by Angamanga — APPROVED** [review]
Works fine! Approved 🎉

**Comment by Angamanga** [comment]
@Obadha2 Ready for QA!

**Comment by Obadha2** [comment]
QA'd, passes. :+1:

**Pull request merged**
