### PR TITLE
2394-fixed-settings-state

### PR DESCRIPTION
**Pull request by Somaru-chan**
This pull request makes the following changes:
- Changed the active state on Settings to include sub-routes. So Settings would remain highlighted in yellow whenever a sub-route is visited.  

Testing checklist:
- [ ] Login as admin
- [ ] Open Settings page
- [ ] Click on any sub-route (General, Surveys, Data Sources.. etc.) 
- [ ] Notice on the left that Settings is now highlighted in yellow. 

- [x] I certify that I ran my checklist

Fixes ushahidi/platform# .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by Somaru-chan** [comment]
[clabot:check]

**Comment by Somaru-chan** [comment]
[clabot:check]

**Comment by Somaru-chan** [comment]
[clabot:check]

**Comment by Somaru-chan** [comment]
Hi @Angamanga @rowasc . Could you please let me know if my PR requires any modifications?

**Comment by Angamanga** [comment]
@Somaru-chan Thank you! I will review shortly!

**Comment by Angamanga** [comment]
@Somaru-chan It looks like the linter is failing. Could you fix it? You test it by running `gulp eslint` in your terminal.

**Comment by Somaru-chan** [comment]
> @Somaru-chan It looks like the linter is failing. Could you fix it? You test it by running `gulp eslint` in your terminal. I see the following error in the logs:
> 
> ```
> /home/runner/work/platform-client/platform-client/app/common/directives/mode-bar/mode-bar.directive.js
>   21:1  error  Parsing error: Unexpected token ) ```
> ```

@Angamanga Fixed. Thanks for bringing it to my attention :)

**Comment by Angamanga** [comment]
@Somaru-chan Thank you!

**Comment by Somaru-chan** [comment]
> @Somaru-chan Thank you!

Hi @Angamanga . I'm aware you must be extremely busy, but this is my first PR and I won't qualify unless it's approved. If it needs any modification at all, please let me know :)

**Review by rowasc — COMMENTED** [review]
Not sure if you or  @Angamanga already checked, but wouldn't this be more in the lines of ```ui-sref-active="{ 'active' : 'settings.*' }" ```` , similar to what we do for the data view button? 

BTW this PR is not wrong. Just want to check because I think this (the ng-class setup manually with $state) was the workaround that was needed at an older version, and then it was fixed? 


Dropping a couple of references (don't feel obligated to dig into them just want to make sure I don't forget them) 
https://stackoverflow.com/questions/22054391/angular-ui-router-how-do-i-get-parent-view-to-be-active-when-navigating-to-ne 

https://github.com/angular-ui/ui-router/commit/bf163ad6ce176ce28792696c8302d7cdf5c05a01

**Review by Angamanga — APPROVED** [review]
This works fine now! Thank you @Somaru-chan!

**Comment by Angamanga** [comment]
@rowasc I remember testing different ways before writing the guide in the issue, but I maybe missed something.

**Comment by rowasc** [comment]
That's alright then, thanks @Angamanga 
@Obadha2 this is ready for testing!

**Comment by Obadha2** [comment]
QA'd, passes. 👍

**Comment by tuxpiper** [comment]
@all-contributors please add @Somaru-chan for code

**Pull request merged**
