### PR TITLE
Date picker fix

### PR DESCRIPTION
**Pull request by Angamanga**
This pull request makes the following changes:
- Pauses the focus-trap when the date-picker is active
- Unpauses the focus-trap when the date-picker is closed
- Adjust the width to date/date-time fields when creating a post so all information is visible.

Testing checklist:
For filters
- Open the filter-dropdown
- Click on start-date or end-date
- [ ] Date-picker is opened
- [ ] It should be possible to select a date
- [ ] The filter-dropdown should remain open when the date-picker is open
- [ ] Repeat above for navigation with keyboard, tab to the start/end-date instead of clicking on it

For date-time field in post-creation
- Add a post for a survey that has a date/time field, select a date and time
- [ ] The whole selected date and time should be visible in the input box after selection.

- [x] I certify that I ran my checklist

Fixes ushahidi/platform#4190 .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by Angamanga** [comment]
@Ifycode Would you mind reviewing this PR?

**Comment by Ifycode** [comment]
ok @Angamanga I have checked it out and played with it a lot. It all works. About the part where the filter-dropdown should remain open when the date-picker is open... I'm not sure how to access that part marked in red using keyboard keys in the screenshot below. So I tried clicking that portion. The dropdown closes even when the picker is still open in this case. 

flatpickr-md

**Comment by Angamanga** [comment]
@Ifycode @tuxpiper I have fixed the remaining issue now, could one of you please review 🎉

**Review by Ifycode — APPROVED** [review]
It works fine now! 🎉 Looks like it miraculously fixes another issue I was going to raise. Nice!

**Review by tuxpiper — APPROVED** [review]
Allelujah! :pray:

**Comment by Angamanga** [comment]
@Obadha2 Ready for QA 🎉 🎉 🎉

**Comment by Obadha2** [comment]
QA'd, passes. :+1:

**Pull request merged**
