### PR TITLE
1000 image upload

### PR DESCRIPTION
**Pull request by jasonmule**
This pull request makes the following changes:
- Add image field to post type

Test these changes by:
- Add an image field to a post type
- Create a new post with the post type and upload an image
- The image should be uploaded and referenced as a post value.
- The image should be shown in the post list as well as post detail views

Fixes ushahidi/platform#1000 .

Ping @ushahidi/platform

---
This change is [Reviewable](https://reviewable.io/reviews/ushahidi/platform-client/167)

### CODE REVIEW

**Comment by jasonmule** [comment]
@rjmackay Could you take a look. I haven't integrated Glide yet. Also, I have disabled setting the media field to 'required' for the time being.

**Comment by rjmackay** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks broke.

---

*[app/post/post-module.js, line 23 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/167#-KGJoKayJX9SArZ3LfmC:-KGJoKazciQ3bXvXtxkv:-1886164766) ([raw file](https://github.com/ushahidi/platform-client/blob/24b1cb32e93b6e037d941324b995ca5360a670a1/app/post/post-module.js#L23)):*
If the module is in common, then we should be registering the service in the common module, not in the post-module.

---

*[app/post/directives/post-editor-directive.js, line 204 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/167#-KGJpTd9IdmbdfnVayHr:-KGJpTdA8FL5GcWeHkKu:537824398) ([raw file](https://github.com/ushahidi/platform-client/blob/24b1cb32e93b6e037d941324b995ca5360a670a1/app/post/directives/post-editor-directive.js#L204)):*
maybe do the concat above so its clearer whats happening?
ie.
```
var requests = Array.concat(deleteMedia(), uploadMedia());
```
NB: I'm sure that Array.concat syntax doesn't look like that.. but something similar anyway.

---

*[app/post/directives/post-editor-directive.js, line 302 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/167#-KGJpuE4yw2j0ijg8Aws:-KGJpuE4yw2j0ijg8Awt:-1704887643) ([raw file](https://github.com/ushahidi/platform-client/blob/24b1cb32e93b6e037d941324b995ca5360a670a1/app/post/directives/post-editor-directive.js#L302)):*
Are we distinguishing image upload vs file upload at all?

---

*[app/post/directives/post-editor-directive.js, line 339 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/167#-KGJqKQWBf0C4Yfq5sGv:-KGJqKQWBf0C4Yfq5sGw:1916277571) ([raw file](https://github.com/ushahidi/platform-client/blob/24b1cb32e93b6e037d941324b995ca5360a670a1/app/post/directives/post-editor-directive.js#L339)):*
Could you do the media attribute init work here? this is already looping all attributes..

---

*[app/post/directives/post-editor-directive.js, line 348 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/167#-KGJtjFgv4iUvrVpmoBY:-KGJtjFhTdUNf2T4q2eJ:322444159) ([raw file](https://github.com/ushahidi/platform-client/blob/24b1cb32e93b6e037d941324b995ca5360a670a1/app/post/directives/post-editor-directive.js#L348)):*
Could any of this move to its own directive along with the file upload markup??

---

*[app/post/directives/views/post-view-list-directive.js, line 39 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/167#-KGJsqdC7ue9OjH26uZb:-KGJsqdC7ue9OjH26uZc:-2009995899) ([raw file](https://github.com/ushahidi/platform-client/blob/24b1cb32e93b6e037d941324b995ca5360a670a1/app/post/directives/views/post-view-list-directive.js#L39)):*
This loop should almost definitely move into the post-preview-directive OR maybe even a post-preview-media directive as mentioned below..

We already load the post form in preview directive - so we can avoid duplicating work here.

---

*[server/www/templates/posts/detail.html, line 87 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/167#-KGJtEimjR1dCCOa6gLn:-KGJtEimjR1dCCOa6gLo:1294285966) ([raw file](https://github.com/ushahidi/platform-client/blob/24b1cb32e93b6e037d941324b995ca5360a670a1/server/www/templates/posts/detail.html#L87)):*
I wonder if this would be any cleaner if it were shifted to its own directive that just handled loading media for the post??

also what happens with multiple image fields? are they combined here? or split out with other post values below??

---

*[server/www/templates/posts/post-editor.html, line 249 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/167#-KGJsQWvvsMvi-IZUkqM:-KGJsQWvvsMvi-IZUkqN:571608753) ([raw file](https://github.com/ushahidi/platform-client/blob/24b1cb32e93b6e037d941324b995ca5360a670a1/server/www/templates/posts/post-editor.html#L249)):*
Could we move this into its own directive? similar to post-relation and post-location

---

*[server/www/templates/posts/preview.html, line 10 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/167#-KGJsYZy3m8UyYe0iOMm:-KGJsYZy3m8UyYe0iOMn:-817235806) ([raw file](https://github.com/ushahidi/platform-client/blob/24b1cb32e93b6e037d941324b995ca5360a670a1/server/www/templates/posts/preview.html#L10)):*
If we added a post-preview-media directive for this - could we move the accompanying controller logic into that?

---

*[server/www/templates/settings/forms/form-edit.html, line 127 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/167#-KGJtxecpQh3I4_VOh-l:-KGJtxecpQh3I4_VOh-m:1832235486) ([raw file](https://github.com/ushahidi/platform-client/blob/24b1cb32e93b6e037d941324b995ca5360a670a1/server/www/templates/settings/forms/form-edit.html#L127)):*
double check this isn't breaking existing fields. ng-if creates a new scope in the child elements.

---

*[server/www/templates/settings/forms/form-edit.html, line 161 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/167#-KGJu8F1l8evTt7rt6Vs:-KGJu8F1l8evTt7rt6Vt:136731574) ([raw file](https://github.com/ushahidi/platform-client/blob/24b1cb32e93b6e037d941324b995ca5360a670a1/server/www/templates/settings/forms/form-edit.html#L161)):*
whats the issue with upload fields being required??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ushahidi/platform-client/167)*

**Comment by rjmackay** [comment]
@willdoran could you input on this too?

Its a pretty good demonstration of refactoring needed in the client code base - particularly around post editing - its quite hard to add this in in a clean way. Everything ends up in large nested controllers... 
But we can probably only do some small tidy up right now and just take note of further work that would make this easier.

**Comment by jasonmule** [comment]
*[server/www/templates/settings/forms/form-edit.html, line 161 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/167#-KGJu8F1l8evTt7rt6Vs:-KGMWgUDUeOu4DLuaKwQ:125139563) ([raw file](https://github.com/ushahidi/platform-client/blob/24b1cb32e93b6e037d941324b995ca5360a670a1/server/www/templates/settings/forms/form-edit.html#L161)):*
I had an issue trying to track uploaded files. Will look at doing this through a directive.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ushahidi/platform-client/167)*

**Comment by jasonmule** [comment]
*[server/www/templates/posts/detail.html, line 87 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/167#-KGJtEimjR1dCCOa6gLn:-KGMXHpF9wk5dA6NZbsh:1935658441) ([raw file](https://github.com/ushahidi/platform-client/blob/24b1cb32e93b6e037d941324b995ca5360a670a1/server/www/templates/posts/detail.html#L87)):*
For now, only the first image is shown.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ushahidi/platform-client/167)*

**Comment by jasonmule** [comment]
*[server/www/templates/posts/detail.html, line 87 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/167#-KGJtEimjR1dCCOa6gLn:-KGMXabZGSNn_Kr-SsXk:-2117569639) ([raw file](https://github.com/ushahidi/platform-client/blob/24b1cb32e93b6e037d941324b995ca5360a670a1/server/www/templates/posts/detail.html#L87)):*
It might make more sense to show them with form values though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ushahidi/platform-client/167)*

**Comment by jasonmule** [comment]
*[app/post/directives/post-editor-directive.js, line 302 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/167#-KGJpuE4yw2j0ijg8Aws:-KGNgQA15MhY4PkUe_pm:702269500) ([raw file](https://github.com/ushahidi/platform-client/blob/24b1cb32e93b6e037d941324b995ca5360a670a1/app/post/directives/post-editor-directive.js#L302)):*
Do we need to? My thinking was that this will be used to upload media only for posts.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ushahidi/platform-client/167)*

**Comment by jasonmule** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks broke.

---

*[app/post/post-module.js, line 23 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/167#-KGJoKayJX9SArZ3LfmC:-KGhvON_4ua-w4_zD-So:-499146009) ([raw file](https://github.com/ushahidi/platform-client/blob/24b1cb32e93b6e037d941324b995ca5360a670a1/app/post/post-module.js#L23)):*
Done.

---

*[app/post/directives/post-editor-directive.js, line 204 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/167#-KGJpTd9IdmbdfnVayHr:-KGhv-FsqydQMxWSFgrl:-1241417465) ([raw file](https://github.com/ushahidi/platform-client/blob/24b1cb32e93b6e037d941324b995ca5360a670a1/app/post/directives/post-editor-directive.js#L204)):*
Moved this to separate directive.

---

*[app/post/directives/post-editor-directive.js, line 339 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/167#-KGJqKQWBf0C4Yfq5sGv:-KGhv7N5qqMwF5jTSpLF:1082055525) ([raw file](https://github.com/ushahidi/platform-client/blob/24b1cb32e93b6e037d941324b995ca5360a670a1/app/post/directives/post-editor-directive.js#L339)):*
Moved to separate directive

---

*[app/post/directives/post-editor-directive.js, line 348 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/167#-KGJtjFgv4iUvrVpmoBY:-KGhvAC7S0mvSGoM1-dc:-499146009) ([raw file](https://github.com/ushahidi/platform-client/blob/24b1cb32e93b6e037d941324b995ca5360a670a1/app/post/directives/post-editor-directive.js#L348)):*
Done.

---

*[app/post/directives/views/post-view-list-directive.js, line 39 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/167#-KGJsqdC7ue9OjH26uZb:-KGhvBq-k8ebxY0tD9xi:-499146009) ([raw file](https://github.com/ushahidi/platform-client/blob/24b1cb32e93b6e037d941324b995ca5360a670a1/app/post/directives/views/post-view-list-directive.js#L39)):*
Done.

---

*[server/www/templates/posts/detail.html, line 87 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/167#-KGJtEimjR1dCCOa6gLn:-KGhvU4ixqkADeII0klD:-499146009) ([raw file](https://github.com/ushahidi/platform-client/blob/24b1cb32e93b6e037d941324b995ca5360a670a1/server/www/templates/posts/detail.html#L87)):*
Done.

---

*[server/www/templates/posts/post-editor.html, line 249 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/167#-KGJsQWvvsMvi-IZUkqM:-KGhvEl6UUtr9H6QPita:-499146009) ([raw file](https://github.com/ushahidi/platform-client/blob/24b1cb32e93b6e037d941324b995ca5360a670a1/server/www/templates/posts/post-editor.html#L249)):*
Done.

---

*[server/www/templates/posts/preview.html, line 10 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/167#-KGJsYZy3m8UyYe0iOMm:-KGhvFpPp3rF0hTdBl_a:-499146009) ([raw file](https://github.com/ushahidi/platform-client/blob/24b1cb32e93b6e037d941324b995ca5360a670a1/server/www/templates/posts/preview.html#L10)):*
Done.

---

*[server/www/templates/settings/forms/form-edit.html, line 127 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/167#-KGJtxecpQh3I4_VOh-l:-KGhvIzO__NN4IA_CCTd:-499146009) ([raw file](https://github.com/ushahidi/platform-client/blob/24b1cb32e93b6e037d941324b995ca5360a670a1/server/www/templates/settings/forms/form-edit.html#L127)):*
Done.

---

*[server/www/templates/settings/forms/form-edit.html, line 161 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/167#-KGJu8F1l8evTt7rt6Vs:-KGhvI9Y1Ewb_O3QMJJZ:-499146009) ([raw file](https://github.com/ushahidi/platform-client/blob/24b1cb32e93b6e037d941324b995ca5360a670a1/server/www/templates/settings/forms/form-edit.html#L161)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ushahidi/platform-client/167)*

**Comment by willdoran** [comment]
@rjmackay I've actually just completed a slight refactor of the post-editor that breaks it apart into the editor, status and stages. When the media upload lands I'll reintegrate develop into my branch.

I've broken out a lot of the overlapping code into a PostEditService which handles cleaning the values, checking if a post is saveable and checking the state of stages.

The code looks good, I'll read it more later.

**Comment by rjmackay** [comment]
Excellent - ship this thing!

---

Reviewed 11 of 22 files at r2.
Review status: 14 of 25 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[app/post/directives/post-editor-directive.js, line 302 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/167#-KGJpuE4yw2j0ijg8Aws:-KGiDM7BSkhuPWEo1z-f:161211577) ([raw file](https://github.com/ushahidi/platform-client/blob/24b1cb32e93b6e037d941324b995ca5360a670a1/app/post/directives/post-editor-directive.js#L302)):*
We'll probably do both later. But I think you're right - it really doesn't matter right now, for this code :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ushahidi/platform-client/167#-:-KGiECcCDzP5ZcaEV_6o:-909213645)*

**Pull request merged**
