### PR TITLE
Fix: Post lock issues (combined fix)

### PR DESCRIPTION
**Pull request by Ifycode**
#### This pull request makes the following changes
- Fixes ushahidi/platform#4428
- Fixes ushahidi/platform#4291
- Fixes ushahidi/platform#4459

#### Testing checklist
- [x] All frontend lock-related issues fixed according to https://ushahidi.slack.com/archives/CFC4WQG4V/p1660302071404769
- [x] I certify that I ran my checklist

[Backend PR for post-lock found here](https://github.com/ushahidi/platform/pull/4444)
Ping @ushahidi/platform

### CODE REVIEW

**Comment by Ifycode** [comment]
@tuxpiper This PR for all post lock fix is completed, and ready for review at last 🥳🥳🥳 🤸🏻‍♀️🤸🏻‍♀️🤸🏻‍♀️

**Comment by tuxpiper** [comment]
@webong could you please review it?

**Comment by tuxpiper** [comment]
@webong  Is a review of this feasible for you?

**Review by webong — APPROVED** [review]

**Comment by webong** [comment]
> @webong Is a review of this feasible for you?

Yes, code details and implementation all looks good to me.

@AmTryingMyBest can take it from here.

**Comment by AmTryingMyBest** [comment]
QA'd, passes. 👍

**Pull request merged**
