### PR TITLE
Fix: Users should be able to see the lock status of a post on the post-edit view

### PR DESCRIPTION
**Pull request by Ifycode**
#### This pull request makes the following changes
- Fixes ushahidi/platform#4459

#### Testing checklist
- [x] Lock icon now shows up on data view's right side
- [x] I certify that I ran my checklist

Ping @ushahidi/platform

### CODE REVIEW

**Comment by Ifycode** [comment]
@tuxpiper this is ready for review

**Review by tuxpiper — APPROVED** [review]
This seems to work :+1: 

Screenshot 2022-08-10 at 22 57 01

Nice lock icon near the title :)

I am going to add the folks for Procoders so they can see some of the tweaks that @Ifycode did here. Most interested in the comment as this code change seems to be engineered to work around some limitations.

Pinging @ushahidi/procoders for comment.

**Comment by tuxpiper** [comment]
Good for QA :+1: Although @AmTryingMyBest maybe you will prefer to test it together with #1815, once it's ready , as that will bring in the rest of Locking information to the screen.

**Comment by Ifycode** [comment]
I'd suggest closing this PR, since #1815 Contains all lock fixes including this lock icon fix. Please help review #1815 instead, as all frontend lock-related fixes are in there - it is ready for review now.

**Comment by tuxpiper** [comment]
Closing in favor of #1815

**Pull request closed without merging**
