### PR TITLE
Data-view: Displaying colours on post-cards in list

### PR DESCRIPTION
**Pull request by Angamanga**
This pull request makes the following changes:
- Reads the survey-colour from the correct variable

Testing checklist:
- Make sure there is a post from a survey configured with a colour 
- Go to data-view
- [ ] Look at the list to the left, the posts connected to the survey should have a colour-band on the left of the card.
- [x] I certify that I ran my checklist

Fixes ushahidi/platform#4303 (the client-side of the issue) .

Ping @ushahidi/platform

### CODE REVIEW

**Review by tuxpiper — APPROVED** [review]
Looks good to me :)

**Comment by Angamanga** [comment]
@Obadha2 Ready for QA 🎉

**Comment by tuxpiper** [comment]
This goes together with #1707 for a full fix

**Comment by tuxpiper** [comment]
This goes together with #1713 for a full fix

**Comment by Obadha2** [comment]
QA'd, passes. 👍

**Pull request merged**
