### PR TITLE
fix: Populate manual lat / lon entry with current location

### PR DESCRIPTION
**Pull request by rjmackay**
- Populate manual lat / lon entry on load
- Populate manual lat / lon entry when map is clicked
- Populate manual lat / lon entry when search result chosen
- Populate manual lat / lon entry when current location used
- Show location lat/lon entry below the map on post detail view

Refs: https://github.com/ushahidi/platform-sivico/issues/33

Testing checklist:
- [x] Edit a post with a location
- [x] See lat / lon is shown when edit loads
- [x] Click on map. See lat /lon is updated
- [x] Search for a location and chose a result. See lat /lon is updated
- [x] Click in search and select 'use my current location'. See lat /lon is updated
- [x] Edit lat / lon. Click Update Map. See map updates
- [x] View a post. See `lat, lon` displayed below map

Ping @ushahidi/platform

### CODE REVIEW

**Comment by rjmackay** [comment]
@willdoran 

> Click in search and select 'use my current location'. See lat /lon is updated

Were you testing over https? I believe browsers block pulling user location on insecure pages.

> View a post. See lat, lon displayed below map

I just retested and this is working for me. Where did you test? Which post?

**Comment by willdoran** [comment]
@rjmackay Tested both locally

- Current location worked correctly to find the location but didn't update the fields
- No lat long were displayed under the map 

But it does appear to be working on the deployment so perhaps it's an edge case?

**Comment by rjmackay** [comment]
> Current location worked correctly to find the location but didn't update the fields

Ok confirmed this breaks on my local too. Let me fix it :(

**Comment by rjmackay** [comment]
> Current location worked correctly to find the location but didn't update the fields

This is now fixed. The update was running outside the angular digest cycle and so not being rendered.

Also fixed some missing translation strings for 'Update map' and 'No matching locations.'

**Comment by rjmackay** [comment]
FYI the auto deployment for this seems a bit broken because its trying to hit the lumen/staging API

**Pull request merged**
