### PR TITLE
Category Selector Field Bug Fix - Resolves #2455

### PR DESCRIPTION
**Pull request by Guzzler**
This pull request makes the following changes:
- Added an ng-if condition to the category selector html file to render only if categories.length > 0.

Fixes ushahidi/platform#2455 .

Ping @ushahidi/platform @rowasc

### CODE REVIEW

**Comment by Guzzler** [comment]
[clabot:check]

**Comment by Angamanga** [comment]
@Guzzler Thank you so much for contributing 🎉 ! I will review this pr and get back to you shortly!

**Comment by Guzzler** [comment]
hey @Angamanga would you prefer that be part of this PR itself? or i make a new one? Not sure what the better approach would be considering this is linked to this Issue itself?

**Comment by Guzzler** [comment]
Have pushed another commit doing the needful. Please let me know if you required something different. I think this should give the desired behavior required. Glad to help and would love to keep contributing! @Angamanga

**Comment by Angamanga** [comment]
@all-contributors please add @Guzzler for code

**Pull request merged**
