### PR TITLE
Code coverage phase 2

### PR DESCRIPTION
**Pull request by willdoran**
[Review on Reviewable](https://reviewable.io/reviews/ushahidi/platform-client/108)

### CODE REVIEW

**Comment by jasonmule** [comment]
Test coverage looks good! How come we call `spyOn` on Notify instead of the endpoints?

---

Review status: 0 of 50 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/e2e/user-profile-e2e-spec.js, line 41 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/108#-KC1vgdEbi7FkXH7bdl5:-KC1vgdEbi7FkXH7bdl6:-893680538) ([raw file](https://github.com/ushahidi/platform-client/blob/fd4afc4fa4113d0a1a14df330a91306ac9a9fada/test/e2e/user-profile-e2e-spec.js#L41)):*
How come this changed?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ushahidi/platform-client/108#-:-KC2-hiL_0aNdClTXJX1:-712539707)*

**Comment by willdoran** [comment]
I do it on the notify because the endpoints there are just mocks. The different notifies occur when the result passes or fails so I wanted to make sure it failed/passed when expected. 
Do you think that works ok?

---

Review status: 0 of 50 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/e2e/user-profile-e2e-spec.js, line 41 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/108#-KC1vgdEbi7FkXH7bdl5:-KC46QAQwmIvVBSMDkOV:1075343242) ([raw file](https://github.com/ushahidi/platform-client/blob/fd4afc4fa4113d0a1a14df330a91306ac9a9fada/test/e2e/user-profile-e2e-spec.js#L41)):*
I wanted to see what the minimum wait we needed was to speed up the tests. This made barely any difference :/ 

But I did discover you can parallel the spec tests, which helped. I'm going to setup travis to run them in parallel so we don't have to wait 20mins for the tests to complete. 

I'll hopefully had that in phase 3 :)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ushahidi/platform-client/108#-:-KC467GZi15dEP7dnVcn:1880934044)*

**Comment by rjmackay** [comment]
Late - but here's some feedback.

---

Reviewed 9 of 50 files at r1.
Review status: 9 of 50 files reviewed at latest revision, 5 unresolved discussions.

---

*[.jshintrc, line 22 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/108#-KCE8yiP8HT8lADosh4Z:-KCE8yiQW_wgF5UmzZEA:1755033433) ([raw file](https://github.com/ushahidi/platform-client/blob/fd4afc4fa4113d0a1a14df330a91306ac9a9fada/.jshintrc#L22)):*
Nope.. underscore was intentionally not global, you're supposed to declare that dependency. Despite it getting dumped in the global namespace anyway.

Doesn't matter now - but I'd like to work towards reducing our globals dependencies over time..

---

*[app/post/directives/post-active-filters-directive.js, line 26 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/108#-KCE7xD1XaUjhvLz2F-9:-KCE7xD253oQWm4k-R9V:-822311558) ([raw file](https://github.com/ushahidi/platform-client/blob/fd4afc4fa4113d0a1a14df330a91306ac9a9fada/app/post/directives/post-active-filters-directive.js#L26)):*
Why are we binding this to scope?  If its not used directly in the markup it shouldn't get exposed...

---

*[app/post/directives/post-view-filters-directive.js, line 115 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/108#-KCE8PgBMqUZjjTCQ-38:-KCE8PgBMqUZjjTCQ-39:-1526953677) ([raw file](https://github.com/ushahidi/platform-client/blob/4d31c74eef59eb76660d1dffe64bebc16767c2c4/app/post/directives/post-view-filters-directive.js#L115)):*
where did these go? Does the datpicker still open and close when you click in the date field after this?

---

*[test/protractor-conf.js, line 14 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/108#-KCE8eYl0AuMdU2qcaPc:-KCE8eYl0AuMdU2qcaPd:-127170676) ([raw file](https://github.com/ushahidi/platform-client/blob/fd4afc4fa4113d0a1a14df330a91306ac9a9fada/test/protractor-conf.js#L14)):*
Does this mean we have to don't automatically pick up new test folders now? (not an issues, just checking..)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ushahidi/platform-client/108#-:-KCE9I56v2cVO2r9zrFq:-1335691632)*

**Comment by willdoran** [comment]
Review status: 9 of 50 files reviewed at latest revision, 5 unresolved discussions.

---

*[app/post/directives/post-active-filters-directive.js, line 26 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/108#-KCE7xD1XaUjhvLz2F-9:-KCGuQt2LA5VKCvDuZrf:521439202) ([raw file](https://github.com/ushahidi/platform-client/blob/fd4afc4fa4113d0a1a14df330a91306ac9a9fada/app/post/directives/post-active-filters-directive.js#L26)):*
I changed to the binding to allow testing from the unit test. This was the most direct way to access the function. However, I think that the function can also be accessed through a sub object of the isolateScope. 

I'll revert that in the next iteration.

---

*[app/post/directives/post-view-filters-directive.js, line 115 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/108#-KCE8PgBMqUZjjTCQ-38:-KCGrz4OMtmcZX1lAFgg:-2010015705) ([raw file](https://github.com/ushahidi/platform-client/blob/4d31c74eef59eb76660d1dffe64bebc16767c2c4/app/post/directives/post-view-filters-directive.js#L115)):*
No, these functions were unused, I believe because of the change to a new datepicker ui lib. 

Though looking at the date range filter, the end date flyout is badly aligned and appears off the page to the right. I'll make an issue for that.

---

*[test/protractor-conf.js, line 14 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform-client/108#-KCE8eYl0AuMdU2qcaPc:-KCGtS3A08kxYHUgJqGa:-17112516) ([raw file](https://github.com/ushahidi/platform-client/blob/fd4afc4fa4113d0a1a14df330a91306ac9a9fada/test/protractor-conf.js#L14)):*
No, in fact, my intention was that this option let us define how we wanted to the specs to be sharded but it doesn't appear to work in that way.

I think it would be good practice though to add suites and specs to explicitly define what is to be tested and to allow exclusion of tests.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ushahidi/platform-client/108)*

**Comment by rjmackay** [comment]
Ok so weirdly this breaks the e2e tests on my local machine. I'd guess its probably the change in delays.. I can investigate further right now so I might revert this before doing a bugfix release

**Comment by willdoran** [comment]
It might also be the parallel testing, the protractor tests running locally are fragile. Activity on the local machine can cause them to fail. I think this may be because they are using a real browser as opposed to headless.

**Pull request merged**
