### PR TITLE
Fixed the deployment to heroku

### PR DESCRIPTION
**Pull request by ps-19**
This pull request makes the following changes:
After brain storming for many hours on heroku and repo i got the silly reason for the issue. 

Testing checklist:
- [x] I have tested the build.

- [x] I certify that I ran my checklist

Fixes ushahidi/platform#[4288](https://github.com/ushahidi/platform/issues/4288).

Ping @ushahidi/platform

### CODE REVIEW

**Comment by Angamanga** [comment]
@tuxpiper Could you review this? 🙏

**Comment by tuxpiper** [comment]
I think that's fine, but since it's the develop branch, a disclaimer should be added that the deployed site may not work or be usable (unstable version).

Otherwise, it should point to the "main" branch instead.

Could you please adjust @ps-19 ?

**Review by tuxpiper — CHANGES_REQUESTED** [review]
Changes requested

**Comment by ps-19** [comment]
@tuxpiper sir where should i add the disclaimer, in the readme file. And even if it is pointing towards `main` still "No app.json located in the repo URL provided" is showing.

**Comment by tuxpiper** [comment]
Oh I see, so it looks like we are actually missing more bits here in order to make this PR viable..

@Angamanga do you recall if we had that app.json before and was removed as part of the Single-SPA changes?

**Comment by tuxpiper** [comment]
I think that without that missing `app.json` file, we should close this PR. Anyone willing to spend a few minutes, I'm pretty sure they can fish that out from previous commits.

**Pull request closed without merging**
