### PR TITLE
#4119 - Fix skipped links in toolbar area of map page

### PR DESCRIPTION
**Pull request by Ifycode**
This pull request makes the following changes:
- Fixes ushahidi/platform#4119

**Issues, observation & steps taken:**
- Sort & filter and share links are skipped when navigating with the tab key, as they were links that had no href.
- In smaller devices, span.mode-context-trigger is skipped. 
- Converted them both to button so that the focus set for buttons in the pattern library will work on them. 

**Associated platform pattern library PRs:**
- [Platform pattern library PR 1](https://github.com/ushahidi/platform-pattern-library/pull/258).

- [Platform pattern library PR 2](https://github.com/ushahidi/platform-pattern-library/pull/259).

**Testing checklist:**
- [x] Add assets folder from platform-pattern-library containing the new changes made to the platform-client which also contains some new changes and run the project.
- [x] Login, and use tab key to navigate the toolbar on the map page.
- [x] Check that buttons are not skipped.
- [x] Check that it is clear to user that a button is in focus.

- [x] I certify that I ran my checklist

Fixes ushahidi/platform# .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by Angamanga** [comment]
@Ifycode Is this ready for review?

**Comment by Ifycode** [comment]
Yes @Angamanga This is ready for review.

**Review by Angamanga — APPROVED** [review]
Thank you for your contribution 🎉  Approved!

**Comment by Ifycode** [comment]
Yay! Thanks @Angamanga

**Comment by Angamanga** [comment]
@Obadha2 Ready for QA. Styling-changes are in this pr: https://github.com/ushahidi/platform-client/pull/1627

**Review by Angamanga — APPROVED** [review]

**Comment by Obadha2** [comment]
QA'd, passes. 👍

**Pull request merged**
