### PR TITLE
Fix: Post list display only published posts by default when no status is specified

### PR DESCRIPTION
**Pull request by Ifycode**
#### This pull request makes the following changes:
- Fixes ushahidi/platform#4468

#### Testing checklist
- [x] All posts are displayed when no status is ticked in post toolbar
- [x] I certify that I ran my checklist

Ping @ushahidi/platform

### CODE REVIEW

**Comment by Ifycode** [comment]
This is ready for review @tuxpiper @webong

**Comment by tuxpiper** [comment]
@webong  could you please review?

**Review by webong — APPROVED** [review]

**Comment by tuxpiper** [comment]
@AmTryingMyBest ready for QA 👍 

(@webong  / @Ifycode : going forward, please ensure that you notify QA when review is complete. I can only check these so often ;) )

**Comment by Ifycode** [comment]
> @AmTryingMyBest ready for QA 👍 
> 
> (@webong  / @Ifycode : going forward, please ensure that you notify QA when review is complete. I can only check these so often ;) )

Alright @tuxpiper

**Comment by tuxpiper** [comment]
Reverting changes on develop, as it was agreed this didn't result in an improvement.

**Pull request merged**
