### PR TITLE
Load scripts when needed

### PR DESCRIPTION
**Pull request by Angamanga**
This pull request makes the following changes:
- Removes Facebook-sdk (was not used)
- Loads Intercom-script when logging in instead of for all users
- Removes old doorbell script

Testing checklist:
- Go to share-> select Facebook
- [x] You should get directed to Facebook (i.e no changes to current behaviour, it should still work)
- Make sure you are logged out and localstorage is cleared
- Make sure you have an app-id in config.js
- Login
- [x] Intercom-script should load (check network tab)]

- [x] Intercom bubble should appear (if new messages to show)

- Logout
- [x] Chatbox should disappear
- Login again
- [x] Intercom-script is already present in window and should not load again.
- [x] Intercom chatbox should appear
- [x] Intercom bubble should appear (if new messages to show)
- [x] I certify that I ran my checklist

Fixes ushahidi/platform# .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by Angamanga** [comment]
@tuxpiper PR for removing and moving scripts 👍

**Comment by Angamanga** [comment]
@tuxpiper This one needs a review

**Review by tuxpiper — APPROVED** [review]
Looks good to me :+1:

**Comment by Angamanga** [comment]
@Obadha2 Ready for QA!

**Comment by tuxpiper** [comment]
@Angamanga any open issue that this is associated with? Or shall we open one for it?

**Comment by Angamanga** [comment]
I cannot find any issues so maybe we just talked about it :)

**Comment by Angamanga** [comment]
@tuxpiper Ready for review (was once approved but need another approval since I added back the chatbox)

**Review by tuxpiper — DISMISSED** [review]

**Comment by tuxpiper** [comment]
For QA: the Intercom behavior will only be testable in steve-buscemi , which requires me to deploy manually.

@Obadha2 please  let me know once you would like to proceed with testing this.

**Comment by tuxpiper** [comment]
Oh I see I added the "QA by dev" flag here, hopefully we talked about that, but I don't remember already @Angamanga  😅 Do you think this is fair? Could you do the QA?

**Comment by Angamanga** [comment]
@Angamanga Do QA

**Comment by Angamanga** [comment]
QA passes in develop 👍

**Pull request merged**
