### PR TITLE
4258 - Moment to dayjs

### PR DESCRIPTION
**Pull request by Ifycode**
#### This pull request makes the following changes:
-  Fixes issue ushahidi/platform#4258

#### Details:
- Installs dayjs (for gradual removal of momentjs).
- Replace moment with dayjs in the files (and routes) listed in the table below.

| Page url     | Files - 12/12 completed |
|----------------|---------------|
| /views/data | <ul><li>- [x] post-metadata.directive.js</li><li>- [x] post-view-data.directive.js</li></ul>|
| /posts/:postId/edit | <ul><li>- [x] post-toolbox.directive.js</li><li>- [x] post-data-editor.directive.js</li></ul>|
| /activity | <ul><li>- [x] activity.controller.js</li></ul>|
| /posts/:postId | <ul><li>- [x] post-value.directive.js</li><li>- [x] post-messages.directive.js</li></ul>|
| /posts/create/:id | <ul><li>- [x] post-editor.directive.js</li></ul>|
| others | <ul><li>- [x] post-datetime-value.directive.js</li><li>- [x] demo-deployment.directive.js</li><li>- [x] tos.service.js</li><li>- [x] translation.service.js</li></ul> |

| Files with unused moment imports - 4/4 completed  |
|----------------|
| <ul><li>- [x] data-import.directive.js</li><li>- [x] data-import.service.js</li><li>- [x] filter-post-order-asc-desc.directive.js</li><li>- [x] filter-post-sorting-options.directive.js</li></ul> |

| Spec files - 7/7 completed |
|----------------|
| <ul><li>- [x] post-view-data.directive.spec.js</li><li>- [x] post-toolbox.directive.spec.js</li><li>- [x] post-detail-data.directive.spec.js</li><li>- [x] post-editor.directive.spec.js</li><li>- [x] tos.service.spec.js</li><li>- [x] post-messages.directive.spec.js</li><li>- [x] mock-modules.js</li></ul> |

| Config - 2/2 completed |
|----------------|
| <ul><li>- [x] app.js</li><li>- [x] webpack config </li></ul>|

#### Testing checklist:
- [x] Check that date and time formatting still work as before in the files above.
- [x] I certify that I ran my checklist

Ping @ushahidi/platform

### CODE REVIEW

**Comment by Angamanga** [comment]
A guide to where to see different files:

_post-messages.directive.js_
This is the "Conversation with author" feature that appears when a post is received from email or SMS in the `/posts/:postId` route. You need to set up SMS or email to see this view; an example of how it looks:
Screenshot 2021-06-04 at 06 06 07

_post-data-editor.directive.js_
This contains the whole edit-view: `/posts/:postId/edit`

_post-datetime-value.directive.js_
The date-time-field when adding or editing a post for a survey with  a "date-time" field

_post-editor.directive.js_
This is a very confusing name for the form that is visible when adding a post `posts/create/:id`

_demo-deployment.directive.js_
This notification box notified a user that their "demo-plan" is expiring and that they can just add 25 posts, etc. I don't think we use it right now, but if you want to check it, you can adjust https://github.com/ushahidi/platform-client/blob/develop/app/common/auth/demo-deployment.service.js#L12 and run `Notify.demo()` without checking the site.tier first. Whenever you reload the page after that, I think you will see the notification.

_translation.service.js_
This one has no own view. It contains functions that help switch languages, switches the view to rtl if needed, and load the locale files from moment. This *may* be the trickiest part depending on how day.js handles it. 😬 

_tos.service.js_
This notification-modal appears on deployments hosted by us (on ushahidi.io) whenever a new user registers or whenever our terms of service change. You can see the modal if you run `Notify.confirmTos()` without doing the if-check before: https://github.com/ushahidi/platform-client/blob/develop/app/common/auth/tos.service.js#L49

_activity.controller.js_
This is the activity-view, `/activity`

Let me know if you wonder anything. This is quite a massive change in many places 🎉

**Comment by Ifycode** [comment]
Thank you @Angamanga

**Comment by Ifycode** [comment]
I'm through with this task @Angamanga

**Review by Angamanga — APPROVED** [review]
Looks good! Approved and well done!

**Comment by Angamanga** [comment]
@Obadha2 Ready for QA. This needs a smoke-test, with a special focus on all the places where we show a date, for example in posts, post-details, post-card in map-view and also in the activity-view.

**Comment by Angamanga** [comment]
@Obadha2 Ready for QA 🎉

**Review by Angamanga — APPROVED** [review]
Approved

**Pull request merged**
