### PR TITLE
Cache contacts

### PR DESCRIPTION
**Pull request by rjmackay**
This pull request makes the following changes:
- Cache contacts from API
- Ensure we *dont* use the cache when editing notifications

Testing checklist:
- [x] Log in as an admin
- [x] Load individual post view of a post from SMS/Twitter. Confirm that contacts are shown

User profile test:
- [x] Browser 1: login
- [x] Browser 2: Login as the same user
- [x] Browser 2: Open user profile & notification settings
- [x] Browser 2: Edit your contacts + save
- [x] Browser 1: Open user profile and confirm you see latest contacts (not old cached info)

Depends on https://github.com/ushahidi/platform-client/pull/894 #896

Ping @ushahidi/platform

### CODE REVIEW

**Comment by rjmackay** [comment]
http://qa.cache-contacts.ushahidilab.com/

**Comment by jshorland** [comment]
@rjmackay In this one, it's not showing author via twitter when i load posts. 
screen shot 2017-10-26 at 7 50 29 pm

**Comment by jshorland** [comment]
Latest contact info is shown though!

**Comment by rjmackay** [comment]
> In this one, it's not showing author via twitter when i load posts.

thats fixed by the other PR. It should work again now I merged that. Wait 5 mins for it to deploy.
If you go direct to a `posts/1234` type url it should work

**Comment by jshorland** [comment]
BOOM. FIXED. PASSES QA!

**Pull request merged**
