### PR TITLE
Add flatpickr library for date picker

### PR DESCRIPTION
**Pull request by renujain31**
This pull request makes the following changes:
- Adds a new date picker library, [flatpickr](https://github.com/flatpickr/flatpickr), to make the datepicker accessible and removes the angular-datepicker library used earlier.

Testing checklist:
- [ ] Open the filters and navigate to the date field.
- [ ] The datepicker opens up and you can navigate through the dates using the arrows.
image

- [ ] Create a new survey that requires the datetime field.
- [ ] Add a post to that survey.
- [ ] The datepicker does have a time field too and you can set the date and time.
image

- [ ] Create a new survey that requires the date field.
- [ ] Add a post to that survey.
- [ ] The datepicker only have the date field and you can navigate through the dates using the arrows. 
image

- [ ] Go to the activity menu.
- [ ] Select Custom date range from the dropdown menu at top.
- [ ] The datepicker only have the date field and you can navigate through the dates using the arrows. 
image

- [ ] I certify that I ran my checklist

Fixes ushahidi/platform#4190 .

Ping @ushahidi/platform

### CODE REVIEW

**Review by Angamanga — APPROVED** [review]
Approved!! 🎉 It is such a nice change 😍

**Comment by Angamanga** [comment]
@Obadha2 Ready for QA!

**Comment by tuxpiper** [comment]
Please check if this behavior (in Firefox only) is fixed by this change:

**Comment by tuxpiper** [comment]
@Angamanga this is not mergeable due to a merge conflict. Please ping @Obadha2 again once that's resolved.

**Comment by Angamanga** [comment]
@Obadha2 Fixed conflicts & ready for QA 🎉

**Comment by tuxpiper** [comment]
Looks like we have failing tests now

**Comment by tuxpiper** [comment]
Looks like we have failing tests now 🔴

**Review by Angamanga — APPROVED** [review]

**Comment by Angamanga** [comment]
@Obadha2 Ready for QA 🎉

**Review by Angamanga — APPROVED** [review]

**Comment by Obadha2** [comment]
@Angamanga cc @renujain31
- on the filters, when I click on arrow on calendar to navigate months, the filter overlay is dismissed. That is an issue. 
- Where there's a Date Time Field, can we expand the width of the field so that when you've selected a date and time, then I can see my selection full and not have some time characters cut out? (see screenshot)
Screenshot from 2021-05-24 16-03-44

**Comment by Angamanga** [comment]
@Obadha2 I see the issues, hope to fix them by tomorrow 👍 .

**Comment by Angamanga** [comment]
@Obadha2 For issue 1, I need this PR in order to fix this one: https://github.com/ushahidi/platform-client/pull/1661.
For issue 2, I cannot reproduce it now, and the field size looks alright for me. What window width did you use? What browser? Do you remember? This is what it looks like for me today:
Screenshot 2021-05-25 at 11 55 07

**Comment by Obadha2** [comment]
@Angamanga For issue 2, I'm using Chrome, on Ubuntu. I zoomed out to 100% but it still doesn't show all the values. Reducing browser window sizes does not change this field.

**Comment by Obadha2** [comment]
Issues fixed.
Passes. :+1:

**Pull request merged**
