### PR TITLE
fix labels on survey-creation

### PR DESCRIPTION
**Pull request by helen-ndip**
This pull request makes the following changes:
- fixed labels by associating them to their various inputs 

Testing checklist:
- [x] I added `for` attribute to label `name` to focus input field name when label is clicked in attribute editor
- [x] I added `for` attribute to label `Make responses private` to activate corresponding toggle button in attribute editor
- [x] I added `for` attribute to labels and `id` attribute to corresponding input fields to enhance focus in Survey editor
- [x] I added `for`  and `id` attributes to label and corresponding textarea field in targeted question modal to enhance focus.
- [x] I added `for`  and `id` attributes to label and corresponding input field in create task to enhance focus.
- [x] I certify that I ran my checklist

Fixes ushahidi/platform#4089 .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by helen-ndip** [comment]
> Hey @helen-ndip,
> thank you for your Pull Request.
> 
> It looks like you haven't signed our **C**ontributor **L**icense **A**greement, yet.
> 
> > The purpose of a CLA is to ensure that the guardian of a project's outputs has the necessary ownership or grants of rights over all contributions to allow them to distribute under the chosen licence.
> > [Wikipedia](http://en.wikipedia.org/wiki/Contributor_License_Agreement)
> 
> You can read and sign our full Contributor License Agreement [here](https://docs.google.com/forms/d/15LyeKTOP36T5u3290o4hsmqv79v-m_s2QSmgMJXpYp8/viewform).
> 
> Once you've signed reply with `[clabot:check]` to prove it.
> 
> Appreciation of efforts,
> 
> clabot

[clabot:check]

**Comment by Angamanga** [comment]
@helen-ndip Could you add a testing-checklist to this pr please?

**Comment by helen-ndip** [comment]
> @helen-ndip Could you add a testing-checklist to this pr please?

done

**Comment by Angamanga** [comment]
@helen-ndip Thank you! I will review shortly!

**Review by Angamanga — APPROVED** [review]
Works fine! Thank you for your contribution!

**Comment by Angamanga** [comment]
@Obadha2 Ready for QA! 🎉

**Comment by Obadha2** [comment]
QA'd, passes. 👍

**Pull request merged**
