### PR TITLE
Fixes custom field description not saving

### PR DESCRIPTION
**Pull request by ryanchristo**
This pull request makes the following changes:
- adds attribute instructions model to description input

Testing checklist:
- [x] When I change the description for a custom field and save, the changes are saved

Fixes ushahidi/platform#1787.

Ping @ushahidi/platform

### CODE REVIEW

**Comment by Angamanga** [comment]
@ryanchristo Thank you so much for your submission! @willdoran or @rjmackay This looks good to me, could you double-check if it is the instructions-column in the form_attributes tables that should be used here, or the description-column in the form_stages? Also, I do not find anywhere in the pattern-library where this description is used. Should it be only in the attributes-edit-field or should it be displayed when adding/viewing posts too? Not sure how the discussions went when designing this?

**Comment by willdoran** [comment]
@Angamanga I'm not completely sure, I'll have to look at the data model.

**Comment by rjmackay** [comment]
This looks good to me. However we should make sure the `instructions` field is actually displayed on the survey form too!

@ryanchristo do you think you could add that as well? I think it need to use a pattern similar to "Form field with instructions" shown here: http://preview.ushahidi.com/platform-pattern-library/develop/assets/html/2_fragments/#pl-pattern-forms
in the `post-value-edit` directive. That really just amounts to a `<p>{{ attribute.instructions }}</p>` after the label, before the input

**Comment by ryanchristo** [comment]
@rjmackay Post form updated with attribute instructions.

**Comment by ryanchristo** [comment]
@rjmackay Attribute instructions added.

**Pull request merged**
