### PR TITLE
Make account settings accessible

### PR DESCRIPTION
**Pull request by renujain31**
This pull request makes the following changes:
- Makes account settings accessible

Testing checklist:
- [ ] Log in to your account.
- [ ] Open account settings by clicking on your profile picture.
- [ ] The modal that opens would be accessible.

- [x] I certify that I ran my checklist

Recording:
account_settings

Fixes ushahidi/platform#4194 .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by Angamanga** [comment]
@renujain31 This works fine! One thing I thing I thought about when testing, that you can add either to this pr or to a new one, is scrolling the edit-modal into view when a thing is focused. If you go to the notifications-view for example, and click on "Add account", the email-address field doesn't scroll into view, it stays hidden beneath the cancel/save-bar:

**Comment by Angamanga** [comment]
@renujain31 Nevermind my comment above, I created a new issue for scrolling-into-view when focussed. Its happening in more modals than this one. https://github.com/ushahidi/platform/issues/4199

**Review by Angamanga — APPROVED** [review]
Approved 🎉

**Comment by Angamanga** [comment]
@Obadha2 Ready for QA! 🦖

**Comment by Angamanga** [comment]
@Obadha2 Conflicts fixed!

**Comment by Obadha2** [comment]
@Angamanga I can't tab into Notifications tab from General tab.

**Comment by Obadha2** [comment]
QA'd, passes. 👍

**Pull request merged**
