### PR TITLE
added isEmbed and small markup change in post-toolbar

### PR DESCRIPTION
**Pull request by GabrielFalcom**
This pull request makes the following changes:
- Remove warnings about non-unique ids in the console

Testing checklist:

- Open the dev-tools

- Click on Console tab

 [ ] You should not see warnings about non-unique ids

 [ ] I certify that I ran my checklist

Fixes ushahidi/platform#4076 .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by GabrielFalcom** [comment]
clabot:check

**Review by Angamanga — APPROVED** [review]
Nice solution! Thank you for your contribution 🎉

**Comment by Angamanga** [comment]
@Obadha2 This is ready for QA!

**Comment by Angamanga** [comment]
@GabrielFalcom Could you add a short test-checklist for our QA-process? Thank you 🎉

**Comment by GabrielFalcom** [comment]
Thank you ;)

**Comment by GabrielFalcom** [comment]
> @GabrielFalcom Could you add a short test-checklist for our QA-process? Thank you 🎉

@Angamanga  Added!

**Comment by rowasc** [comment]
@Obadha2 this can be tested ! :tada:

**Comment by Obadha2** [comment]
QA'd, passes. 👍

**Comment by Obadha2** [comment]
This doesn't quite pass QA. Warning messages for non-unique IDs still appear on the console. They specifically appear when you click on avatar on left menu bar (above the logout button). 

> QA'd, passes. 👍

**Comment by GabrielFalcom** [comment]
In the profile modal, there are two tabs, General and notification, which render two inputs with the same id and name (email). If there is no problem, I can change the id and name of the notification tab to email-radio, and that would resolve this warning.

**Comment by Angamanga** [comment]
@Obadha2 Thank you! @GabrielFalcom Yes, it sounds like its the same problem as with the tool-bar. Please go ahead with the change 🙏 .

**Pull request merged**
