### PR TITLE
Feature/form roles 1282

### PR DESCRIPTION
**Pull request by zhalloran**
This pull request makes the following changes:
- Adds a toolbox with a required approval toggle & survey permission menu to the survey-edit view.
- Modifies the Add post button so that it filters survey types based on based on whether or not the current role as permission to do so.

Test these changes by:
- Log in as admin and go to /settings/surveys/:survey_id
- Click on the `Require posts be reviewed before they're published` toggle
- Click on the `Survey Permissions` menu
- Click on the `Specific Roles` option
- Select which roles have access
- Test permission by going to /views/maps and logging in with different roles

Fixes ushahidi/platform#1282 .

Ping @ushahidi/platform

---
This change is [Reviewable](https://reviewable.io/reviews/ushahidi/platform-client/307)

### CODE REVIEW

**Comment by zhalloran** [comment]
@rjmackay If it makes sense to do so, I'd prefer to add a `can-add` field to the `form` payload instead of executing 3 requests in the add-post-button directive to test for permission to post. If you're cool with that, I'll work on that at the same time as I make updates to the Post Authorizer & Form repo in the API.

**Comment by rjmackay** [comment]
@zhalloran I think that makes sense. Probably `can_add` with an underscore to match other fields.

**Comment by rjmackay** [comment]
Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

*[app/post/views/add-post-button.directive.js, line 75 \[r2\]](https://reviewable.io:443/reviews/ushahidi/platform-client/307#-KQYqjlEXH2ghPiJhZ5J:-KQYqjlEXH2ghPiJhZ5K:b-urd07y) ([raw file](https://github.com/ushahidi/platform-client/blob/5ece6380a126fe3dc898cfa24fd7e8a2dc8da95e/app/post/views/add-post-button.directive.js#L75)):*
> ```JavaScript
>         var allowed_forms = $q.defer();
>         
>         FormEndpoint.query()
> ```

Ideally we should do this filter on the backend, ie. pass a query param like forms?can_create=1

---

*[app/post/views/add-post-button.directive.js, line 78 \[r2\]](https://reviewable.io:443/reviews/ushahidi/platform-client/307#-KQYqyTZv3CvZ-xkV1Ij:-KQYqyTZv3CvZ-xkV1Ik:b2wdkhl) ([raw file](https://github.com/ushahidi/platform-client/blob/5ece6380a126fe3dc898cfa24fd7e8a2dc8da95e/app/post/views/add-post-button.directive.js#L78)):*
> ```JavaScript
>         .$promise
>         .then(function(forms) {
>             if (!$rootScope.isAdmin()) {
> ```

this should actually be a permissions check ie. hasPermission('Manage Posts')

---

*[app/post/views/add-post-button.directive.js, line 79 \[r2\]](https://reviewable.io:443/reviews/ushahidi/platform-client/307#-KQYs-SUclbLuF-9yX4T:-KQYs-SVPOaRsFp6ByCZ:b-nalgp5) ([raw file](https://github.com/ushahidi/platform-client/blob/5ece6380a126fe3dc898cfa24fd7e8a2dc8da95e/app/post/views/add-post-button.directive.js#L79)):*
> ```JavaScript
>         .then(function(forms) {
>             if (!$rootScope.isAdmin()) {
>                 _.each(forms, function(form, index) {
> ```

This would be better done using `_.filter()`

---

*[app/setting/directives/setting-survey-editor.directive.js, line 89 \[r2\]](https://reviewable.io:443/reviews/ushahidi/platform-client/307#-KQYsZLG3ebU-iP2wrTz:-KQYsZLG3ebU-iP2wrU-:bgkmfa1) ([raw file](https://github.com/ushahidi/platform-client/blob/5ece6380a126fe3dc898cfa24fd7e8a2dc8da95e/app/setting/directives/setting-survey-editor.directive.js#L89)):*
> ```JavaScript
>             // pre-fill object with default tasks and attributes
>             
> 	        RoleEndpoint.query().$promise.then(function (roles) {
> ```

You should be able to avoid all this extra mapping by using http://vitalets.github.io/checklist-model/ in the template instead.

---

*[server/www/templates/settings/surveys/modify/editor.html, line 80 \[r2\]](https://reviewable.io:443/reviews/ushahidi/platform-client/307#-KQYsrT48xhEbXBwQwkJ:-KQYsrT48xhEbXBwQwkK:bssbcox) ([raw file](https://github.com/ushahidi/platform-client/blob/5ece6380a126fe3dc898cfa24fd7e8a2dc8da95e/server/www/templates/settings/surveys/modify/editor.html#L80)):*
> ```HTML
>                     <div class="tool">
>                         <div class="form-field switch">
>                             <label>Require posts be reviewed before they're published</label>
> ```

You need to use ng translate for these strings ie. `<label translate='some.key.here'>`

---

*[server/www/templates/settings/surveys/modify/editor.html, line 120 \[r2\]](https://reviewable.io:443/reviews/ushahidi/platform-client/307#-KQYvXkOquwF1NLSIYeX:-KQYvXkOquwF1NLSIYeY:b-5m1s7e) ([raw file](https://github.com/ushahidi/platform-client/blob/5ece6380a126fe3dc898cfa24fd7e8a2dc8da95e/server/www/templates/settings/surveys/modify/editor.html#L120)):*
> ```HTML
>                                             <use xlink:href="../../img/iconic-sprite.svg#people"></use>
>                                         </svg>
>                                         <input class="init" name="survey-add" id="survey-add_roles" value="false" ng-modaldata-fieldgroup-toggle="survey-add_roles" type="radio" ng-model="survey.everyone_can_create">
> ```

what does ng-modaldata-fieldgroup-toggle do?

---

*[server/www/templates/settings/surveys/modify/editor.html, line 124 \[r2\]](https://reviewable.io:443/reviews/ushahidi/platform-client/307#-KQYvpDJ_2kpwCtSOaL7:-KQYvpDKIi8PvZ0QMYhs:bsd7qdr) ([raw file](https://github.com/ushahidi/platform-client/blob/5ece6380a126fe3dc898cfa24fd7e8a2dc8da95e/server/www/templates/settings/surveys/modify/editor.html#L124)):*
> ```HTML
>                                     </label>
> 
>                                     <div class="form-fieldgroup init" data-fieldgroup-target="survey-add_roles" ng-class="{true:'', false:'active'}[survey.everyone_can_create]">
> ```

I think your ng-class is backwards. It should be `ng-class='{ active :  !survey.everyone_can_create }'`

---

*[server/www/templates/settings/surveys/modify/editor.html, line 127 \[r2\]](https://reviewable.io:443/reviews/ushahidi/platform-client/307#-KQYw91UeeE9hQPzVZ0F:-KQYw91UeeE9hQPzVZ0G:b-76qoao) ([raw file](https://github.com/ushahidi/platform-client/blob/5ece6380a126fe3dc898cfa24fd7e8a2dc8da95e/server/www/templates/settings/surveys/modify/editor.html#L127)):*
> ```HTML
> 	                                    
>                                         <div class="form-field checkbox" ng-repeat="role in roles">
>                                             <input id="survey-add_roles-members_{{role.id}}" value="{{role.id}}" type="checkbox" ng-checked="role.is_allowed" ng-disabled="role.is_admin" ng-model="roles_allowed" ng-click="updateRoles(role.id)">
> ```

This would probably be easier if you use checklist-model (http://vitalets.github.io/checklist-model/)

Add `<input checklist-model="roles_allowed" checklist-value="role.id">` .. then you can drop the ng-click and ng-checked entirely

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ushahidi/platform-client/307)*

**Comment by rjmackay** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks broke.

---

*[app/setting/directives/setting-survey-editor.directive.js, line 424 \[r2\]](https://reviewable.io:443/reviews/ushahidi/platform-client/307#-KQZ0ITPwalTxNgaYs5-:-KQZ0ITQIfK-ii4S-sWW:b-x44gca) ([raw file](https://github.com/ushahidi/platform-client/blob/5ece6380a126fe3dc898cfa24fd7e8a2dc8da95e/app/setting/directives/setting-survey-editor.directive.js#L424)):*
> ```JavaScript
>         
>         // convert survey.everyone_can_create values to Boolean
>         if ($scope.survey.everyone_can_create == 'true') {
> ```

You shouldn't need to do this. Use ng-value in the template

---

*[app/setting/directives/setting-survey-editor.directive.js, line 439 \[r2\]](https://reviewable.io:443/reviews/ushahidi/platform-client/307#-KQZ0bxeXYNju_0NyUOf:-KQZ0bxeXYNju_0NyUOg:bt8n0eo) ([raw file](https://github.com/ushahidi/platform-client/blob/5ece6380a126fe3dc898cfa24fd7e8a2dc8da95e/app/setting/directives/setting-survey-editor.directive.js#L439)):*
> ```JavaScript
>             // Second save the survey tasks
>             saveTasks();
>             saveRoles();
> ```

We should probably be waiting for roles and tasks promises to return.. but I guess saveTasks was already this way :/

---

*[app/setting/directives/setting-survey-editor.directive.js, line 501 \[r2\]](https://reviewable.io:443/reviews/ushahidi/platform-client/307#-KQZ0RcvMif96-P9Hd8Y:-KQZ0RcwneiGHiowh0B5:bar6aha) ([raw file](https://github.com/ushahidi/platform-client/blob/5ece6380a126fe3dc898cfa24fd7e8a2dc8da95e/app/setting/directives/setting-survey-editor.directive.js#L501)):*
> ```JavaScript
>     function saveRoles() {
>         FormRoleEndpoint
>         .saveCache(_.extend({ roles: $scope.roles_allowed }, {formId: $scope.survey.id}))
> ```

No need to use _.extend here, just define this as a single object??

---

*[app/setting/directives/setting-survey-editor.directive.js, line 502 \[r2\]](https://reviewable.io:443/reviews/ushahidi/platform-client/307#-KQZ0X7kid4-dJIBoehV:-KQZ0X7kid4-dJIBoehW:bbnq7qt) ([raw file](https://github.com/ushahidi/platform-client/blob/5ece6380a126fe3dc898cfa24fd7e8a2dc8da95e/app/setting/directives/setting-survey-editor.directive.js#L502)):*
> ```JavaScript
>         FormRoleEndpoint
>         .saveCache(_.extend({ roles: $scope.roles_allowed }, {formId: $scope.survey.id}))
>         .$promise
> ```

You probably want to just return this promise directly

---

*[server/www/templates/settings/surveys/modify/editor.html, line 110 \[r2\]](https://reviewable.io:443/reviews/ushahidi/platform-client/307#-KQZ08HoTinih8zdGO5d:-KQZ08HoTinih8zdGO5e:b-rx3ehq) ([raw file](https://github.com/ushahidi/platform-client/blob/5ece6380a126fe3dc898cfa24fd7e8a2dc8da95e/server/www/templates/settings/surveys/modify/editor.html#L110)):*
> ```HTML
>                                             <use xlink:href="../../img/iconic-sprite.svg#globe"></use>
>                                         </svg>
>                                         <input name="survey-add" id="survey-add_everyone" value="true" checked="" type="radio" ng-model="survey.everyone_can_create">
> ```

Use `ng-value="true"` and then the model should be set to a boolean not a string.
You might actually be able to omit value entirely.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ushahidi/platform-client/307)*

**Pull request merged**
