### PR TITLE
Fix 4081: Check and fix labels on new and edit posts

### PR DESCRIPTION
**Pull request by bimbolabuari**
# Description of Issue

Some labels are not associated with their respective input elements in the create post field. This limits its accessibility, such as an assistive technology like screen reader reading out the label text when the form input is on focus making it easier for assistive technology users to know what data to be entered, also, clicking on an associated label activates it respective input by changing the focus to it, this helps increase the hit area and provides an advantage to a user trying to activate the input.

## Proposed Solution
For input elements with `id` attribute, the respective label is given a `for`  attribute with the same value as with the input's `id` value. For input elements with no `id` attribute, a new `id` is added having the same value with a new `for` attribute for the label elements, for example as shown below:

```
 <label for="long">Long</label>
      <input id="long" type="text" ng-model="manualModel.lon">
```
## Testing
The testing was done manually by clicking on the label elements which in turn focus/activate the associated input element as shown in the screenshot section below. The gulp test command was run to make sure no test is broken/affected by the changes.

Testing checklist:
- [x] I certify that I ran my checklist

- [ ] Log in as admin
- [ ] Click on "Data" in the left-hand mode-bar
- [ ] In the post-view, click on the "+" icon or edit an existing post
- [ ] Create a new survey
- [ ] Click on all label
- [ ] Focus is changed to the associated inputs

## Screenshots
|  Current        |    Proposed changes    |
| --------- |:----------:|
| issue-current-create-post        |      issue-resolve-create-post                   |

 Fixes ushahidi/platform#4081

Ping @ushahidi/platform @Angamanga @rowasc

### CODE REVIEW

**Comment by Angamanga** [comment]
@bimbolabuari Please check this issue: https://github.com/ushahidi/platform/issues/4081 and see if something more needs to be added to this PR.

**Comment by bimbolabuari** [comment]
> @bimbolabuari Please check this issue: [ushahidi/platform#4081](https://github.com/ushahidi/platform/issues/4081) and see if something more needs to be added to this PR.

@Angamanga, I just confirm that this PR also fixes the issue with editing posts. I wasnt able to check this before because i was having an issue with creating a post but this has been solved in https://github.com/ushahidi/platform/issues/2746#issuecomment-714796869 

edit-post-label

**Review by Angamanga — APPROVED** [review]
Approved! Thank you for your contribution!

**Comment by Angamanga** [comment]
@Obadha2 Ready for QA!

**Comment by Obadha2** [comment]
QA'd, passes. 👍

**Pull request merged**
