### PR TITLE
Remove warning ids console

### PR DESCRIPTION
**Pull request by GabrielFalcom**
This pull request makes the following changes:
-Remove warnings about non-unique ids in the console

Testing checklist:

- [x] I certify that I ran my checklist

**Logged Out**
- Open the dev-tools

 - Click on Console tab

- [x] You should not see warnings about non-unique ids

**Logged In**
- Open the dev-tools

- Click on Console tab

- Click on avatar on left menu bar 

- [x] You should not see warnings about non-unique ids

Fixes #1548

Ping @ushahidi/platform

### CODE REVIEW

**Review by rowasc — CHANGES_REQUESTED** [review]
hey @GabrielFalcom , thanks for your contribution. Please remove the new yarn.lock file added. Thanks

**Comment by GabrielFalcom** [comment]
@rowasc It's done : )

**Review by rowasc — APPROVED** [review]
Thanks for the removal of that .lock file. I think this is okay now. Let's test it @Obadha2

**Comment by Obadha2** [comment]
Hi @GabrielFalcom 
This fails QA. The non-unique id warmings persist on the console. When both logged in, or not logged in.
Screen Shot 2020-10-27 at 3 18 20 PM

**Pull request merged**
