### PR TITLE
Adding loading-bar to survey-view

### PR DESCRIPTION
**Pull request by Angamanga**
This pull request makes the following changes:
- Adds a loading-bar/line to the create-survey-screen.

Testing checklist:
- Click on the + sign and select a survey to add a new post to
- [ ]  While the survey is loading, an orange bar/line that is moving should be visible just below the toolbar.

- [x] I certify that I ran my checklist

Fixes ushahidi/platform# .

Ping @ushahidi/platform

### CODE REVIEW

**Review by webong — APPROVED** [review]

**Comment by webong** [comment]
All good to me! 

There's a side-effect I notice though, once I'm done adding a post to a survey, the orange bar/line loader shows, but even after the post is submitted and redirects to its post-view, the load line doesn't go away (keeps loading).

**Comment by Angamanga** [comment]
@webong Yea, that is the functionality of the bar I think, already present in production. Since we use the same bar for most loading events, it shows up whenever a request is done and the client is waiting for a response from the API. It could be loading posts, loading map, checking for exports etc etc.

**Comment by tuxpiper** [comment]
@Angamanga @webong  can we say this is good for QA?

**Comment by tuxpiper** [comment]
@AmTryingMyBest could you please test this at the earliest opportunity? 🙏

**Pull request merged**
