### PR TITLE
Ui fixes data view

### PR DESCRIPTION
**Pull request by Angamanga**
This pull request makes the following changes:
Bugfixes:
> ... is clickable but the whole card is clicked as well @Angamanga

> No x is displayed on leave-edit-mode-warning @Angamanga

> When navigating away from a card after cicking 'continue' or 'save' on the warning-modal, it doesnt continue to where the user was going, I stay on the post-details-view @Angamanga

> I get redirected to a new page altogether when clicking edit in data-view when in saved-search/collection-mode

Testing checklist:
- [ ] when clicking ... in post-card, the whole card is not clicked as well
- [ ] edit button in ... works as expected
- [ ] x is displayed on leave-edit-mode-warning
- [ ] when in edit mode, if i make changes and go to another url (for example map-view) without saving, the warning shows up. If clicking continue, i should be redirected to the view I wanted to go to
- [ ] when in saved-searches or collection-mode and i click edit in data-view, edit-view should appear in the same view (#2135)

Fixes ushahidi/platform# .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by rowasc** [comment]
quick note
> edit button in ... works as expected

In data mode "normal" yes, it opens the edit form. 
In saved search data mode  it opens the edit form. 

The ... context menu is below the data cards, but I don't think is part of the scope of this PR

**Comment by rowasc** [comment]
> edit button in ... works as expected
Actually it only works as expected from the cards, but not from the post view . I'll pull this and see what's going on .

**Comment by rowasc** [comment]
- [x]  when clicking ... in post-card, the whole card is not clicked as well
- [x] edit button in ... works as expected
- [x] x is displayed on leave-edit-mode-warning
- [x] when in edit mode, if i make changes and go to another url (for example map-view) without saving, the warning shows up. If clicking continue, i should be redirected to the view I wanted to go to
- [x] when in saved-searches or collection-mode and i click edit in data-view, edit-view should appear in the same view (#2135)

**Comment by crcommons** [comment]
Should the warning show up when you try to refresh or physically change the url, not just navigate away in the app?

**Comment by crcommons** [comment]
One bug... when you have selected a post and then try to edit it, the dropdown still goes behind the posts. But it works correctly when you have no selected the post. 
screen shot 2017-10-12 at 2 47 07 pm

**Comment by rowasc** [comment]
@crcommons uh. I don't really know if it should. I'll ask around. 
@crcommons the bug I'll post in a different ticket since I think it's related to the PL

**Comment by rowasc** [comment]
OK the answer is yes :D 
I’m going to separate in a different ticket if that’s OK @carolyn just so we can get this one merged since it has some pretty important stuff that blocks users when not applied

**Comment by crcommons** [comment]
Sounds good! Approving now.

**Pull request merged**
