### PR TITLE
Fix 4087: Associate label with input elements

### PR DESCRIPTION
**Pull request by bimbolabuari**
# Description of Issue

Some labels are not associated with their respective input (and select) elements in "Settings" section (general, roles, webhooks).  This limits its accessibility, such as an assistive technology like screen reader reading out the label text when the form input is on focus making it easier for assistive technology users to know what data to be entered, also, clicking on an associated label activates it respective input by changing the focus to it, this helps increase the hit area and provides an advantage to a user trying to activate the input.

## Proposed Solution

For input elements with `id` attribute, the respective label is given a `for` attribute with the same value as with the input's `id` value. For input elements with no `id` attribute, a new `id` is added having the same value with a new `for` attribute for the label elements, for example as shown below

```html
<label for="webhook-url" translate>webhook.url</label>
<input id="webhook-url" type="text" placeholder="{{'webhook.url' | translate}}" ng-model="webhook.url" required>
```

## Testing

The testing was done manually by clicking on the label elements which in turn focus/activate the associated input element as shown in the screenshot section below. The `gulp test` command was run to make sure no test is broken/affected by the changes.

### Testing checklist
- [x] I certify that I ran my checklist

#### General

 - [x] Log in as admin
 - [x] Click on "Settings" in the left-hand mode-bar
 - [x] Click on "General" in the settings list
 - [x] Click on all label
 - [x] Focus is changed to the associated inputs

#### Roles

 - [x] Log in as admin
 - [x] Click on "Settings" in the left-hand mode-bar
 - [x] Click on "Roles" in the settings list
 - [x] In the roles-view, click on the "+" icon.
 - [x] Click on all label 
 - [x] Focus is changed to the associated inputs

 #### Webhook

 - [x] Log in as admin
 - [x] Click on "Settings" in the left-hand mode-bar
 - [x] Click on "webhook" in the settings list
 - [x] In the webhooks-view, click on the "+" icon.
 - [x] Click on all label
 - [x] Focus is changed to the associated inputs

## Screenshots

|  Current        |    Proposed changes    |
| --------- |:----------:|
| General                       |
| ushahidi-platform-general-cc         |      ushahidi-platform-general-pc                    |
|          Role                    |
| ushahidi-platform-role-cc         |  ushahidi-platform-role-pc                    |
|          Webhook                  |
| ushahidi-platform-webhook-cc         |    ushahidi-platform-webhook-pc                  |

Fixes ushahidi/platform#4087

Ping @ushahidi/platform @Angamanga @rowasc

### CODE REVIEW

**Comment by bimbolabuari** [comment]
[clabot:check]

**Review by Angamanga — CHANGES_REQUESTED** [review]
This works fine! Thank you for your contribution! I noticed there are some conflicts to fix, once they are resolved this is ready to be approved 👍

**Comment by bimbolabuari** [comment]
@Angamanga @rowasc,
Thanks, I will resolve the conflict ASAP

**Comment by bimbolabuari** [comment]
@Angamanga, I have resolved the conflict
Thanks

**Comment by Angamanga** [comment]
@bimbolabuari Thank you!

**Review by Angamanga — APPROVED** [review]
This works fine now! Thank you for your contribution!

**Comment by rowasc** [comment]
@Obadha2 ready for testing.

**Comment by bimbolabuari** [comment]
Thank you!

**Comment by tuxpiper** [comment]
I noticed that this fixes the same issue as #1558 (which we just released) . Are we still planning to merge and test this one? (cc: @Obadha2 @Angamanga )

**Comment by Angamanga** [comment]
@tuxpiper Thank you for noticing 👍 @Obadha2 Do not merge this yet. It is still valuable to keep it open for the contributor during the Outreachy application-period but then we can close it.

**Comment by Angamanga** [comment]
Closing due to fixed in https://github.com/ushahidi/platform-client/pull/1558

**Pull request closed without merging**
