### PR TITLE
localhost updated in readme

### PR DESCRIPTION
**Pull request by NidhiKJha**
This pull request makes the following changes:
- updates readme

Testing checklist:
- [ * ]

- [ * ] I certify that I ran my checklist

Fixes ushahidi/platform #1289 

Ping @ushahidi/platform

### CODE REVIEW

**Comment by NidhiKJha** [comment]
[clabot:check]

**Comment by NidhiKJha** [comment]
@Angamanga Can you please review this PR?

**Comment by Angamanga** [comment]
@NidhiKJha Thank you for your contribution 🎉

**Comment by NidhiKJha** [comment]
@Angamanga This has yet to be merged, shall I make some other changes as well?

**Comment by Angamanga** [comment]
@NidhiKJha Fixed :) I will review your other pr shortly!

**Comment by NidhiKJha** [comment]
Thank you @Angamanga :)

**Pull request merged**
