### PR TITLE
Make filter actions bar opaque to make text readable.

### PR DESCRIPTION
**Pull request by noone0212**
This pull request makes the following changes:
- Made filter actions bar 100% opaque to make the text behind readable.

Testing checklist:
- [ ]

- [ ] I certify that I ran my checklist

Fixes ushahidi/platform#2374 .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by noone0212** [comment]
clabot:check

**Comment by noone0212** [comment]
Hi @Erioldoesdesign! 
Please review the changes made.
I added drop shadow to light grey button.
Thanks!

**Comment by Erioldoesdesign** [comment]
@noone0212 Cool! any chance I can see a screenshot? 🙏

**Comment by noone0212** [comment]
@Erioldoesdesign Here's the screenshot-

Screenshot from 2020-02-28 18-04-31

**Comment by Erioldoesdesign** [comment]
@noone0212 perfect! Thank you :)

**Comment by noone0212** [comment]
@rowasc Please review my pull request.

**Comment by Angamanga** [comment]
@noone0212 Thank you for your contribution! I will review shortly!

**Comment by Angamanga** [comment]
@noone0212 Thank you for your contribution, the change looks good! However, there is something odd going on with the branch. Did you create the opaque_bar-branch from master instead of develop perhaps?

To solve this, could you: 
1. Make sure your develop-branch is up to date with the ushahidi-develop branch (it looks like your develop may be 2 commits ahead)
2. Rebase the opaque-branch with develop as the base (more info about this here: https://git-scm.com/docs/git-rebase)
 3. Push your changes and ping me :) 

This would not cause a problem for this particular change, but if master would have had other commits  than develop, with big changes for example, it could have been a problem, so branching off the correct branch is a good habit to get in to.

Thank you!

**Pull request closed without merging**
