### PR TITLE
#4130 Added img role in all svg images to improve accessibility

### PR DESCRIPTION
**Pull request by bukolabisuga**
This pull request makes the following changes:
-

Testing checklist:
- [ ]

- [x] I certify that I ran my checklist

Fixes ushahidi/platform# .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by bukolabisuga** [comment]
Hi @Angamanga @renujain31 
Kindly review this PR for issue #4130

**Comment by bukolabisuga** [comment]
[clabot:check]

**Comment by bukolabisuga** [comment]
Hello @renujain31 @rowasc @Angamanga , Kindly review this PR for the issue #4130 
I would appreciate if the issue can be assigned to me as well
Thank you

**Comment by bukolabisuga** [comment]
Hi @rowasc , here's the PR for the #4130 issue. I look forward to your feedback. Thank you!

**Comment by rowasc** [comment]
Thanks @bukolabisuga ! I'll flag this for Anna for tomorrow since it's near my end of day but if she doesn't get to it I will
@Angamanga LMK if you need me to review :)

**Comment by bukolabisuga** [comment]
> Thanks @bukolabisuga ! I'll flag this for Anna for tomorrow since it's near my end of day but if she doesn't get to it I will
> @Angamanga LMK if you need me to review :)

Thank you for the opportunity @rowasc @Angamanga

**Review by rowasc — APPROVED** [review]
Alright. I just reviewed. This looks good. Normally I'd ask for a detailed checklist but in this case, the QA procedure should be to smoke test icons across the app essentially, it should be OK (if this were functional changes it'd be a different thing entirely)
@Obadha2 please give this a try when you are back :) what this PR does is add an "img" role to each image. The icon SVGs should have that role attribute added.

**Comment by Angamanga** [comment]
@bukolabisuga There are some conflicts in this pr, could you fix them and then we can merge and QA it 👍

**Comment by bukolabisuga** [comment]
> @bukolabisuga There are some conflicts in this pr, could you fix them and then we can merge and QA it 👍

Hi @Angamanga , thanks for the feedback. I've resolved them. Kindly review, thank you!

**Review by Angamanga — APPROVED** [review]

**Comment by Angamanga** [comment]
@Obadha2 Ready for QA. There is no test-checklist but it needs smoke-tests on icons across the app 👍

**Comment by Obadha2** [comment]
QA'd, passes. 👍

**Pull request merged**
