### PR TITLE
Fix 4103: Add alt-text to avatar-images 

### PR DESCRIPTION
**Pull request by bimbolabuari**
# Description of Issue

Some images do not include alternative text as this helps in web accessibility, its primary purpose is for visually impaired users, This limits its accessibility, such as an assistive technology like screen reader reading out the alternative text when on the image, making it easier for assistive technology users to help have a feel/identity an image.

## Proposed solution

 For images without an alternative text, an alternative text "user avatar" is given. For example, as shown below:

```html
  <img alt="user avatar" src="//www.gravatar.com/avatar/{{ message.user.gravatar }}?d=retro&s=40" class="avatar">
```
## Testing

The testing was done manually by turning off the website image and also using a screen reader which in turn shows alternative text. The `gulp test` command was run to make sure no test is broken/affected by the changes.

### Testing checklist:

- [x] I certify that I ran my checklist

- [ ] Turn off website images on site settings
- [ ] Alternatively use a screen reader
- [ ] Click on "Data" in the left-hand mode-bar
- [ ] Click on a current post
- [ ] The alternative text `user avatar` will display 

## Screenshots
|  Current        |    Proposed changes    |
| --------- |:----------:|
| add-alt-text-pervious    |      add-alt-text-later

Fixes ushahidi/platform#4103

Ping @ushahidi/platform @rowasc @Angamanga

### CODE REVIEW

**Comment by Angamanga** [comment]
@bimbolabuari Thank you! I will review shortly, could you also add a "test-checklist" to the description. This is a guide for what to look for when reviewing the pr and doing QA.

**Comment by bimbolabuari** [comment]
@Angamanga, I will make the necessary adjustment to my PR  ASAP
Thanks!

**Comment by bimbolabuari** [comment]
@Angamanga, I have made necessary adjustments to my PR,
Thank you!

**Review by Angamanga — APPROVED** [review]
Approved! Thank you for your contribution!

**Comment by Angamanga** [comment]
@Obadha2 Ready for QA 🎉

**Comment by Obadha2** [comment]
QA'd, passes. 👍

**Pull request merged**
