### PR TITLE
Added some attributes to improve accessibility

### PR DESCRIPTION
**Pull request by error404-sp**
This pull request makes the following changes:
-Fixes input type,svg,button for login and signup form

Testing checklist:
- [ ] Open signup or login form
   In the screen-reader/braile display
*  The svgs are identified.
*  The button is identified as a cancel button.
*  The input for email identifies valid email address

- [x] I certify that I ran my checklist

Fixes ushahidi/platform#4080 .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by error404-sp** [comment]
[clabot:check]

**Comment by error404-sp** [comment]
[clabot:check]

**Comment by rowasc** [comment]
hey @error404-sp thanks for your contribution, please add a description and the checklist you may have used for testing to help reviewers going over it (and link to the corresponding ticket) 

Thanks!

**Comment by error404-sp** [comment]
Hi @rowasc , I have added the description and testing checks.

**Review by rowasc — APPROVED** [review]
This looks good to me @Obadha2 could you test onmonday? 
thanks @error404-sp !

**Comment by renujain31** [comment]
Just a nit comment: Adding the changes in some files while keeping the others same might make this file's code inconsistent with other files. Maybe we can create multiple first-timers issue that can address this changes in all the files? 

I am also just a contributor to the project so have pretty much zero idea on how things are handled. 
@rowasc @Angamanga maybe you can add any views on this?

**Comment by rowasc** [comment]
@renujain31 hey, not sure if you're talking here about multiple PRs addressing different changes in the same files? just asking to be sure

**Comment by renujain31** [comment]
No @rowasc not about making multiple PRs, I was talking about making the code consistent with other files. 

So for example we use the cancel button at many places([like here](https://github.com/ushahidi/platform-client/blob/develop/app/settings/surveys/task-create.html#L21)). It might be a good option to apply the W3C Standards to all the files as that might increase accessibility of Ushahidi platform. So I was suggesting that we create multiple first-timer issues that can address such changes just like Anna created for checking the labels of the forms(ushahidi/platform#4086). This can also help us get more first-timers contributors in the project as it requires minimal understanding of the codebase.

**Comment by Sunairaa** [comment]
Hey @Angamanga is this issue still available?

**Comment by rowasc** [comment]
@Angamanga can you check @renujain31 comment above?  it makes sense to separate in small tickets so more newcomers can get started, for sure, and we get to improve accessibility across the codebase a lot more.
@renujain31 would you be interested to help Anna with that since you had the (great!) idea? Thanks

**Comment by renujain31** [comment]
Ya sure! I would be happy to help. It might be good idea to create a single issue that can track all that multiple issues. Going with that for now.

**Comment by Angamanga** [comment]
@renujain31 Thank you so much for your help!

**Comment by Angamanga** [comment]
@Obadha2 Ready for QA 🎉

**Comment by Obadha2** [comment]
QA'd, passes. 👍

**Comment by tuxpiper** [comment]
@Angamanga could you please confirm if this fixes the issue completely or partially?

**Comment by Angamanga** [comment]
@tuxpiper Completely 👍

**Pull request merged**
