### PR TITLE
V5 main hydration options

### PR DESCRIPTION
**Pull request by rowasc**
This pull request makes the following changes:
- Limits API usage in the platform client to only get the things it needs at each point
- Removed "broken" exports so they aren't being checked every few seconds for eternity, slowing everything down
Testing checklist:
- [x] Survey creation
     - [x] Related posts
     - [x] Categories
     - [x] Translations
- [x] Data view
     - [x] Post view detail
     - [x] Filters
     - [x] Delete, bulk delete, bulk status update, status update
     - [x] translations for posts and their entities
- [ ] General smoke testing required
- [x] Exports (CSV) notifications - verify that when you create an export, and leave the page, you get notified of its completion
- [x] I certify that I ran my checklist

Fixes ushahidi/platform# .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by Angamanga** [comment]
@rowasc This works, have sent a few tiny fixes + needs the unstructured posts-fix from production before merging. I have NOT done a general smoke-test...

**Comment by Angamanga** [comment]
@rowasc The unstructured posts-fix is now included and refactored! 👯

**Comment by Angamanga** [comment]
@Obadha2 Ready for QA. Needs smoke-tests 🎉

**Comment by Obadha2** [comment]
QA'd, passes. 👍

**Pull request merged**
