### PR TITLE
Feat/gmail data source

### PR DESCRIPTION
**Pull request by tuxpiper**
Rework of #1528

This pull request makes the following changes:
- Adds features to enable Gmail Datasource configuration on the settings screen
- Adds a Gmail Auth Modal Directive for authenticating a google auth token

Testing checklist:
- [ ]

- [ ] I certify that I ran my checklist

Fixes ushahidi/platform# .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by tuxpiper** [comment]
@webong please check that this new PR has everything

**Comment by tuxpiper** [comment]
That failure on "Test & Ship / ship (push)" is fine , it's due to the weird branch name

**Comment by webong** [comment]
> @webong please check that this new PR has everything

Yes it does ... thank you.

**Comment by tuxpiper** [comment]
Merging by now into the feature branch for deployment and testing.

Tagging @Angamanga because I think she will find it interesting :)

**Pull request merged**
