### PR TITLE
Intercom Button removal, add to Support menu

### PR DESCRIPTION
**Pull request by willdoran**
This pull request makes the following changes:
- Removes intercom fab button
- Creates Intercom link within Support Links menu item
- Intercom Window now opens to the right of the screen when Intercom support menu item clicked
- Updated intercom config/setup script to handle page refresh or loading of page in new tab.

Testing checklist:
- [x] When logged *out* 
  - [x] I should not be able to see any intercom fab button
  - [x] When I click on the Ushahidi icon in the bottom left hand corner of the screen
    - [x] The Support Menu modal opens
    - [x] There is no Intercom entry in the Support Menu list
- [x] When logged *in* 
    - [x] I should not be able to see any intercom fab button on
      - [x] Map view
      - [x] Data view
      - [x] Settings view
      - [x] Activity view
  - [x] When I click on the Ushahidi icon in the bottom left hand corner of the screen
    - [x] The Support Menu modal opens
    - [x] There is an Intercom entry in the Support Menu list
    - [x] When I click on the Intercom entry I should see an Intercom Messenger window appear to the right of the screen.
  - [x] I refresh the page
    - [x] When I click on the Ushahidi icon in the bottom left hand corner of the screen
    - [x] The Support Menu modal opens
    - [x] There is an Intercom entry in the Support Menu list
    - [x] When I click on the Intercom entry I should see an Intercom Messenger window appear to the right of the screen.
  - [x] I log out
      - [x] When I click on the Ushahidi icon in the bottom left hand corner of the screen
      - [x] The Support Menu modal opens
      - [x] There is no Intercom entry in the Support Menu list
  - [x] I log in
    - [x] When I click on the Ushahidi icon in the bottom left hand corner of the screen
      - [x] The Support Menu modal opens
      - [x] There is an Intercom entry in the Support Menu list
      - [x] When I click on the Intercom entry I should see an Intercom Messenger window appear to the 
      - [x] I log out
      - [x] The intercom messenger window disappears

- [x] I certify that I ran my checklist

Fixes ushahidi/platform# .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by jshorland** [comment]
@willdoran one request: can you change the text under the intercom item in the support modal list from "Contact Ushahidi staff for real time chat support" to "Contact Ushahidi staff for chat support"? Many hours throughout the day, it's not real time response.

**Comment by willdoran** [comment]
Yes I will change that now

**Comment by jshorland** [comment]
Wording fixed. passes QA.

**Comment by rowasc** [comment]
Adding testpad link for future sanity https://ushahidi.ontestpad.com/script/9#34//

**Comment by rowasc** [comment]
@willdoran 
-  I refresh the page
-  The Support Menu modal opens

this means that if I have the support menu open and refresh, it should be re-opened? Because that doesn't happen to me at least

**Comment by willdoran** [comment]
@romina, no it should not automatically reopen you should go through the steps again, including reopening the support menu, I've amended the checklist

**Comment by rowasc** [comment]
@willdoran thanks , that works then

**Comment by rowasc** [comment]
adding the test run report from testpad as a reference \o/ since I realized we didn't really show Will how to run things in testpad yet. 
https://ushahidi.ontestpad.com/script/9/report

**Pull request merged**
