### PR TITLE
Updated ReadMe with instructions for gulp configs

### PR DESCRIPTION
**Pull request by vixadd**
This pull request makes the following changes:
- Updates the JSON config instructions for developers

Test these changes by:
- Successfully ran server via gulp

Fixes ushahidi/platform# .

Ping @ushahidi/platform

---
This change is [Reviewable](https://reviewable.io/reviews/ushahidi/platform-client/344)

### CODE REVIEW

**Comment by rjmackay** [comment]
[clabot:check]

**Comment by rjmackay** [comment]
We actually deprecated gulpconfig.json - you should switch to using a `.env` file.

**Comment by vixadd** [comment]
Thank you for letting me know. Will use `.env` from now on. Is there a slack chat where I can remain in the loop on current issues?

**Comment by rjmackay** [comment]
@vixadd you can join https://gitter.im/ushahidi/Community - this syncs with a channel on our internal slack.
Our internal slack is largely private.. if its easier though I could add you as a guest to the slack channel. Send me an email to robbie@ushahidi.com

**Comment by vixadd** [comment]
Sounds good, I would really love to just get involved with this project. Will look into this.

**Pull request closed without merging**
