### PR TITLE
#3315 Fix translation on modal title for the Spanish Language 

### PR DESCRIPTION
**Pull request by emalindahk**
This pull request makes the following changes:
- Adds `translate` to span for Modal title
- Spanish language characters now appear as expected. 
- The title `Actualizar B&uacute;squeda` appears as `Actualizar Búsqueda`
- The title `Crear B&uacute;squeda Guardada` appears as `Crear Búsqueda Guardada`

Testing checklist:
- Select Spanish as Language on the Languages dropdown
- Go to sort & filters 
- Create a new filter.
- Click on the yellow button  `Guardar Búsqueda` 
- You will see `Crear Búsqueda Guardada`as modal title
- Update the created filter.
- Click on the yellow button `Actualizar Búsqueda`
- You will see `Actualizar Búsqueda` as modal title

- [ ] I certify that I ran my checklist

Fixes ushahidi/platform#3315 .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by emalindahk** [comment]
> [clabot:check]

**Review by rowasc — CHANGES_REQUESTED** [review]
@emalindahk 
Looking good (just checked the screenshot you sent :tada: )
Two comments

1. Can you explain why we are removing all this files? And if the intention is to move them, why? Translations were working without the change so I'm not convinced I want to move all the locale files without a good reason ( if we do end up doing that, we need to also change the gulfile since the locale files are added automatically with a script from there). 
2. did you submit the CLA https://docs.google.com/forms/d/15LyeKTOP36T5u3290o4hsmqv79v-m_s2QSmgMJXpYp8/viewform ?

Thanks!

**Comment by emalindahk** [comment]
> @emalindahk
> Looking good (just checked the screenshot you sent 🎉 )
> Two comments
> 
> 1. Can you explain why we are removing all this files? And if the intention is to move them, why? Translations were working without the change so I'm not convinced I want to move all the locale files without a good reason ( if we do end up doing that, we need to also change the gulfile since the locale files are added automatically with a script from there).
> 2. did you submit the CLA https://docs.google.com/forms/d/15LyeKTOP36T5u3290o4hsmqv79v-m_s2QSmgMJXpYp8/viewform ?
> 
> Thanks!

I moved the file to the app folder to access all the languages in the dropdown. Before that, I could only get the English language in the dropdown.

**Review by Angamanga — APPROVED** [review]
Thank you @emalindahk! This is approved now 🎉

**Comment by Angamanga** [comment]
@Obadha2 Ready for QA 🌮 !

**Comment by Obadha2** [comment]
QA'd, passes. 👍

**Pull request merged**
