### PR TITLE
#4138 Improved header logical tab order

### PR DESCRIPTION
**Pull request by bukolabisuga**
This pull request makes the following changes:
-

Testing checklist:
- [ ]

- [x] I certify that I ran my checklist

Fixes ushahidi/platform# .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by bukolabisuga** [comment]
Hi @rowasc @Angamanga Kindly review this PR for #4138 https://github.com/ushahidi/platform/issues/4138

**Review by Angamanga — CHANGES_REQUESTED** [review]
@bukolabisuga Even if we manage to tab to this, it still doesn't open once it gets focus. I think this is due to the dropdown-functionality we use, it might work if the whole <div> gets focus instead.

**Comment by bukolabisuga** [comment]
Hi @Angamanga , thanks for the feedback!
You are right, you need to tab twice for the dropdown to show,
I can work on improving the experience such that the dropdown shows once you tab into the arrow (if you believe this is a better approach)

**Comment by Angamanga** [comment]
@bukolabisuga Thank you! I think a solution where the dropdown opens once you press space would be the best solution, thats what we have for example in the language-dropdown and other similar places.

**Comment by Angamanga** [comment]
@bukolabisuga Closing this, if you plan to work on it I am happy to reopen :)

**Pull request closed without merging**
