### PR TITLE
Feat/gmail data source

### PR DESCRIPTION
**Pull request by webong**
This pull request makes the following changes:
- Adds features to enable Gmail Datasource configuration on the settings screen
- Adds a Gmail Auth Modal Directive for authenticating a google auth token

Testing checklist:
- [ ]

- [ ] I certify that I ran my checklist

Ping @ushahidi/platform

### CODE REVIEW

**Comment by tuxpiper** [comment]
The language json files shouldn't be in this PR. In fact merging them may cause conflicts , since the files are already there in develop and master .

@webong could you please check if you could address this in your fork?

**Comment by webong** [comment]
I did merge develop to the gmail-support branch to keep it up to date ... I should be able to revert it from my end.

**Comment by tuxpiper** [comment]
mm interesting, I have updated the base branch with the latest from develop too , but it's not looking any better :/ . Now we have a conflict.

**Comment by tuxpiper** [comment]
@webong  I'm going to pull your branch on the main repo and fiddle around if that's fine. Will close this PR and create a new one, once I've got thing settled

**Comment by tuxpiper** [comment]
Closing in favor of #1530

**Pull request closed without merging**
