### PR TITLE
Fix: Text color is not visible for links added to the deployment description

### PR DESCRIPTION
**Pull request by Ifycode**
#### This pull request makes the following changes
- Fixes ushahidi/platform#4450

#### Testing checklist
- [x] Text color is visible for links added to the deployment description
- [x] I certify that I ran my checklist

Ping @ushahidi/platform

### CODE REVIEW

**Comment by Ifycode** [comment]
Ready for review @tuxpiper @webong

**Review by tuxpiper — APPROVED** [review]
Looking good :+1: @AmTryingMyBest good for QA too

**Comment by AmTryingMyBest** [comment]
@Ifycode @tuxpiper this change doesn't seem to have come into effect. 

https://user-images.githubusercontent.com/38259840/183366828-7c0ee3c2-cb4f-462d-90f2-4193f984e062.mov

**Comment by AmTryingMyBest** [comment]
QA'd, passes. 👍

**Pull request merged**
