### PR TITLE
close notifications after a set timeut of 6s or when user navigates f…

### PR DESCRIPTION
**Pull request by helen-ndip**
…rom a page

This pull request makes the following changes:
-

Testing checklist:
- [x] automatically dismiss notification when user navigates away from a page.
- [x] automatically dismiss notification after 6s if user decides to stay on a page.
- [x] I certify that I ran my checklist

Fixes ushahidi/platform#4384.

Ping @ushahidi/platform

### CODE REVIEW

**Review by Angamanga — CHANGES_REQUESTED** [review]
Thank you for your contribution @helen-ndip! I like the solution but I would like to remove the timeout and only keep closing it for navigation-changes. For some of the notifications, the slider actually needs to be open to prevent the user from missing it, for example csv exports so its actually better to keep it.

**Comment by Ako-Njang** [comment]
> Thank you for your contribution @helen-ndip! I like the solution but I would like to remove the timeout and only keep closing it for navigation-changes. For some of the notifications, the slider actually needs to be open to prevent the user from missing it, for example csv exports so its actually better to keep it.

Ok I think so too. I will update that right away.

**Comment by helen-ndip** [comment]
> Thank you for your contribution @helen-ndip! I like the solution but I would like to remove the timeout and only keep closing it for navigation-changes. For some of the notifications, the slider actually needs to be open to prevent the user from missing it, for example csv exports so its actually better to keep it.

I think so too. I will update that right away.

**Comment by helen-ndip** [comment]
@Angamanga  I have done the suggested changes.

**Comment by helen-ndip** [comment]
> Thank you for your contribution @helen-ndip! I like the solution but I would like to remove the timeout and only keep closing it for navigation-changes. For some of the notifications, the slider actually needs to be open to prevent the user from missing it, for example csv exports so its actually better to keep it.

@Angamanga  do I still need to make some more changes? I think I am done with this

**Review by Angamanga — APPROVED** [review]
Thank you for your contribution 🙏 Approved!

**Comment by Angamanga** [comment]
@Obadha2 Ready for QA.

**Comment by Obadha2** [comment]
@Angamanga QA'd, passes. 👍

**Comment by Angamanga** [comment]
@tuxpiper To include in next relase!

**Comment by tuxpiper** [comment]
Wonderful 👌, thank you all!

**Pull request merged**
