### PR TITLE
fix(MapView stats): use the stats endpoint instead of counting the geojson entries since we can get the same info

### PR DESCRIPTION
**Pull request by rowasc**
fix(MapView stats): use the stats endpoint instead of counting the geojson entries since we can get the same info from the stats endpoint. 

This pull request makes the following changes:
- Changes a call to geojson for a call to stats which is less resource intensive.

Testing checklist:
- [ ] Load the map view with a deployment with many posts. 
- [ ] Verify that your filters dropdown displays the correct count for mapped vs unmapped posts (x of y. ) 
      - Note: the wording there is a bit odd because it implies its not showing the full dataset when in reality what is does is show the count of mapped vs totals, but that's a separate thing, didn't want to change it without more talking about it.

- [x] I certify that I ran my checklist

Fixes ushahidi/platform# .

Ping @ushahidi/platform

### CODE REVIEW

**Review by tuxpiper — APPROVED** [review]
Niice :+1: I favor this.

I was just wondering, may there be differences in count due to permissions (not all that familiar with the stats repository code in the API)

**Comment by Angamanga** [comment]
@rowasc @tuxpiper In production right now, we display the result in the filter-dropdown as nb of posts in the search-result vs all posts with *location information*:


With this change, we would display the result as nb of posts vs ALL posts, unmapped and mapped:
Screenshot 2020-11-17 at 11 44 54

Is this a change in behaviour we want to do? For context, we discussed the behaviour here: https://ushahidi.slack.com/archives/C03UU507R/p1598257290004300

**Comment by rowasc** [comment]
@Angamanga ooof sorry I totally missed that was going on . Fixing

**Review by Angamanga — APPROVED** [review]
Works fine 🎉

**Comment by tuxpiper** [comment]
@Obadha2 did this pass QA?

**Pull request merged**
