### PR TITLE
fixed broken link to documentaion page for ushahidi

### PR DESCRIPTION
**Pull request by andrew21-mch**
This pull request makes the following changes:
- changes link https://www.ushahidi.com/support to https://docs.ushahidi.com/ushahidi-platform-user-manual which solved an issue on the ushahidi platform concerning broken link to documentation #4253

- [x] I certify that I ran my checklist
- [x] changed link to the platform user manual

Fixes ushahidi/platform#4253

Ping @ushahidi/platform

### CODE REVIEW

**Comment by andrew21-mch** [comment]
@webong please could you help review this

**Review by Angamanga — APPROVED** [review]
Thank you for your contribution! Approved!

**Comment by Angamanga** [comment]
@Obadha2 Ready for QA

**Comment by andrew21-mch** [comment]
thanks @Angamanga

**Comment by Angamanga** [comment]
@Obadha2 Reminding you to QA this

**Comment by andrew21-mch** [comment]
thanks @Angamanga

**Comment by Obadha2** [comment]
QA'd, passes. 👍

**Comment by andrew21-mch** [comment]
> QA'd, passes. +1

thanks @Obadha2

**Pull request merged**
