### PR TITLE
fix default language not showing on categories

### PR DESCRIPTION
**Pull request by helen-ndip**
This pull request makes the following changes:
-

Testing checklist:
- [ x] Log in and navigate to  /settings/categories/create, the drop-down now has the default language selected.
-  [ x] Log in and navigate to  /settings/surveys/create, the drop-down now has the default language selected.
-  [ x] Language select on the sidebar now has the default language.
- [ x] I certify that I ran my checklist

Fixes ushahidi/platform#4227.

Ping @ushahidi/platform, @Angamanga

### CODE REVIEW

**Comment by helen-ndip** [comment]
@Angamanga  this has the changes you suggested.

**Review by Angamanga — APPROVED** [review]
Excellent! This works fine :) Thank you for your contribution!

**Comment by Angamanga** [comment]
@Obadha2 Ready for review!

**Comment by Obadha2** [comment]
QA'd, passed. 👍

**Comment by Angamanga** [comment]
@tuxpiper For next release!

**Pull request merged**
