### PR TITLE
Date time field

### PR DESCRIPTION
**Pull request by Angamanga**
This pull request makes the following changes:
- Uses the post-value-edit directive for date-field and date-time fields
- Converts and sends the time to the API in UTC 
- Adds timezone information to meta-data

Testing checklist:
- Add a new post to a survey with a date-time field
- [x] Check the post, it should show exactly the same time as you added
- [x] Click on edit, the date visible should still be the same as you added
- Change the value of the field
- [x] Check the post, it should show exactly the same time as you changed to

**Known bug (needs changes in the API): When deleting the value in edit-mode, the date is reset to 1 january 1970.**

- [x] I certify that I ran my checklist

Fixes ushahidi/platform# .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by Angamanga** [comment]
@tuxpiper @webong PR for sending correct date-time values to the API. I have left deleting a value in edit-mode as it is for now, sending an empty string as the value when I want to clear the field.

**Review by tuxpiper — COMMENTED** [review]
Looks good to me, just left a small informative comment :+1: I'm going to leave it for @webong to do more detailed checking with the API perspective in mind and give the final call

**Comment by Angamanga** [comment]
@webong Reminding you to review this one 👍

**Review by webong — APPROVED** [review]

**Comment by webong** [comment]
Tested locally, works as expected 👌🏽. Good to go @Angamanga

**Comment by Angamanga** [comment]
@Obadha2 Ready for QA

**Comment by Angamanga** [comment]
@Obadha2 Did you ever get to QA this one? Did it pass QA?

**Comment by Angamanga** [comment]
@Obadha2 Reminding you to QA this.

**Comment by Obadha2** [comment]
Looks good, passes QA @Angamanga . 👍

**Comment by Angamanga** [comment]
@tuxpiper Passed QA! We can deploy it 🎉

**Comment by tuxpiper** [comment]
ok :+1: deploying . Please note that this one https://github.com/ushahidi/platform-client/pull/1768  also seems to be going out (as it was merged previously)

**Comment by tuxpiper** [comment]
Ah @Angamanga and @webong  I forgot to ask, will we have a way to differentiate when looking at the database which datetimes were submitted after this change, and which ones before?

**Pull request merged**
