### PR TITLE
Add alt tags to gravatar images

### PR DESCRIPTION
**Pull request by joneskj55**
This pull request makes the following changes:
- Adds alt tags to img elements that are displaying avatars.

Testing checklist:
- [x]

- [x] I certify that I ran my checklist

Fixes ushahidi/platform#4103 .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by joneskj55** [comment]
[clabot:check]

**Review by rowasc — APPROVED** [review]
Thanks for your contribution. @joneskj55 . This looks good/follows the spec!


Regardless of that I'd like to ask  @Angamanga a question before we can merge.  I don't think I understand why we would want a screen reader to call out the "user avatar"  image (instead of skipping it) since it's a low signal text/adds noise, no?  but at the same time assume this came from our accessibility reviews and I'm just missing something? sorry I didn't catch this at the ticket-writing stage to ask, just want to make sure I understand it now. 
Walter: hold on merge please.

**Comment by Angamanga** [comment]
@rowasc We could think of it as a decorative image and add an empty alt="" to skip it. I am thinking about users that do see things but not enough and use screen-readers. Wouldn't they get confused if they see that it is something there but not what it is? Its not like there is any other explanation anywhere about what it is.

**Comment by tuxpiper** [comment]
Just adding a note that ushahidi/platform#4103 is also fixed by #1577 (released today)

**Comment by Angamanga** [comment]
@tuxpiper Thank you for noticing, closing this since the repo looks deleted already.

**Pull request closed without merging**
