### PR TITLE
Re-integrate cloud branch

### PR DESCRIPTION
**Pull request by willdoran**
This pull request makes the following changes:
- Remove Config service
- Adds Features service which governs view, feature availability and access to feature limits
- Reintegrates the cloud and core OSS branches

Test these changes by:
- Using the platform api branch feature/cloud-reintegration, feature availability should be configurable and behave as expected for cloud

Fixes ushahidi/platform#813

Ping @ushahidi/platform

---
This change is [Review on Reviewable](https://reviewable.io/reviews/ushahidi/platform-client/121)

### CODE REVIEW

**Comment by rjmackay** [comment]
Good work. This looks much less scary than I expected! The main thing is going to be searching for odd race conditions where the initial state isn't loaded first.. if you have something like CharlesProxy it might be worth testing with throttling turned on to simulate a remote API, might need to clear your localStorage too so you don't get cached Config.

---

Reviewed 1 of 18 files at r3, 2 of 29 files at r4, 1 of 13 files at r5, 9 of 30 files at r6.
Review status: 13 of 60 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[app/activity/controllers/activity-controller.js, line 6 \[r6\]](https://reviewable.io:443/reviews/ushahidi/platform-client/121#-KCS_1o8z5znmf-G4TSV:-KCS_1oCIIng0bRbejn2:2056295520) ([raw file](https://github.com/ushahidi/platform-client/blob/b6fffce6cd0abac4051af422738c0d96bd7aaad0/app/activity/controllers/activity-controller.js#L6)):*
No need for ConfigEndpoint anymore?

---

*[app/common/controllers/page-metadata.js, line 12 \[r6\]](https://reviewable.io:443/reviews/ushahidi/platform-client/121#-KCS_Sel5isLcVb7IGZs:-KCS_Sel5isLcVb7IGZt:1735177207) ([raw file](https://github.com/ushahidi/platform-client/blob/b6fffce6cd0abac4051af422738c0d96bd7aaad0/app/common/controllers/page-metadata.js#L12)):*
I wonder if we should just make the default title 'loading...'

---

*[app/common/global/language-settings.js, line 14 \[r6\]](https://reviewable.io:443/reviews/ushahidi/platform-client/121#-KCS_g1kYIV7psfxKopJ:-KCS_g1kYIV7psfxKopK:980125227) ([raw file](https://github.com/ushahidi/platform-client/blob/b6fffce6cd0abac4051af422738c0d96bd7aaad0/app/common/global/language-settings.js#L14)):*
I think this leaves us with a race condition where language is set below BEFORE this returns.  .. I think a few of the BootstrapConfig things were really just hacks to work around race conditions like this.

---

*[app/common/services/features.js, line 13 \[r6\]](https://reviewable.io:443/reviews/ushahidi/platform-client/121#-KCSaJ3X-GomLmnIsHMg:-KCSaJ3X-GomLmnIsHMh:665261627) ([raw file](https://github.com/ushahidi/platform-client/blob/b6fffce6cd0abac4051af422738c0d96bd7aaad0/app/common/services/features.js#L13)):*
I think we might need to emit an event here. ie. featuresUpdated .. so that controllers etc can listen for changes when this loads.
Otherwise I suspect there's a race condition where ie. home view loads with no views available, because config isn't loaded yet.

We can mitigate a couple of those, by populating sane defaults: ie. map and list views available.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ushahidi/platform-client/121#-:-KCSbGp39SBFdM3tzChq:-1002163803)*

**Comment by willdoran** [comment]
Review status: 8 of 60 files reviewed at latest revision, 4 unresolved discussions.

---

*[app/activity/controllers/activity-controller.js, line 6 \[r6\]](https://reviewable.io:443/reviews/ushahidi/platform-client/121#-KCS_1o8z5znmf-G4TSV:-KCaPnWLCKdtgWLfNRey:-499146009) ([raw file](https://github.com/ushahidi/platform-client/blob/b6fffce6cd0abac4051af422738c0d96bd7aaad0/app/activity/controllers/activity-controller.js#L6)):*
Done.

---

*[app/common/controllers/page-metadata.js, line 12 \[r6\]](https://reviewable.io:443/reviews/ushahidi/platform-client/121#-KCS_Sel5isLcVb7IGZs:-KCaPqon_etN_pMQs5RQ:999423535) ([raw file](https://github.com/ushahidi/platform-client/blob/b6fffce6cd0abac4051af422738c0d96bd7aaad0/app/common/controllers/page-metadata.js#L12)):*
Ha, hmmm, I dunno, if for some reason site name is unset it might get weird,  but it would avoid a branding issue. The more I think about it the more reasonable 'loading...' seems

---

*[app/common/global/language-settings.js, line 14 \[r6\]](https://reviewable.io:443/reviews/ushahidi/platform-client/121#-KCS_g1kYIV7psfxKopJ:-KCaz6gSoXY9DK8Y0px5:-330667133) ([raw file](https://github.com/ushahidi/platform-client/blob/b6fffce6cd0abac4051af422738c0d96bd7aaad0/app/common/global/language-settings.js#L14)):*
Yep, I think so - I've replaced the Bootstrap from master for the moment.

---

*[app/common/services/features.js, line 13 \[r6\]](https://reviewable.io:443/reviews/ushahidi/platform-client/121#-KCSaJ3X-GomLmnIsHMg:-KCazKXRe2QEAxztuibo:1778190257) ([raw file](https://github.com/ushahidi/platform-client/blob/b6fffce6cd0abac4051af422738c0d96bd7aaad0/app/common/services/features.js#L13)):*
Yep, looking at this now

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ushahidi/platform-client/121)*

**Comment by rjmackay** [comment]
Looks good. Some minor queries then squash+land.

---

Reviewed 9 of 21 files at r2, 3 of 18 files at r3, 5 of 29 files at r4, 7 of 13 files at r5, 5 of 30 files at r6, 13 of 17 files at r7.
Review status: 49 of 61 files reviewed at latest revision, 2 unresolved discussions.

---

*[package.json, line 26 \[r7\]](https://reviewable.io:443/reviews/ushahidi/platform-client/121#-KDQ-tzoJXzYkTImPrkS:-KDQ-tzpiEAZzeXyQeWe:1380731258) ([raw file](https://github.com/ushahidi/platform-client/blob/cb27442700e914dce7e75e1149d359102f41c48f/package.json#L26)):*
Was that an intentional change? Not sure we want to auto fix everything without warning

---

*[app/activity/controllers/activity-controller.js, line 20 \[r7\]](https://reviewable.io:443/reviews/ushahidi/platform-client/121#-KDQ098KI5Djbs9_FbrV:-KDQ098LKmXxonJ0RAjE:1486372664) ([raw file](https://github.com/ushahidi/platform-client/blob/cb27442700e914dce7e75e1149d359102f41c48f/app/activity/controllers/activity-controller.js#L20)):*
What shows up while this is loading?? Could we do the loadFeatures() call in the router `resolve` instead?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ushahidi/platform-client/121#-:-KDQ1vGmf9DZ5_iA74Mk:418240585)*

**Comment by willdoran** [comment]
Review status: 49 of 61 files reviewed at latest revision, 2 unresolved discussions.

---

*[package.json, line 26 \[r7\]](https://reviewable.io:443/reviews/ushahidi/platform-client/121#-KDQ-tzoJXzYkTImPrkS:-KDQPifqiRe255R64yEy:637669048) ([raw file](https://github.com/ushahidi/platform-client/blob/cb27442700e914dce7e75e1149d359102f41c48f/package.json#L26)):*
I'll change it back!

---

*[app/activity/controllers/activity-controller.js, line 20 \[r7\]](https://reviewable.io:443/reviews/ushahidi/platform-client/121#-KDQ098KI5Djbs9_FbrV:-KDQodHOUpwyMI--s7mU:677588487) ([raw file](https://github.com/ushahidi/platform-client/blob/cb27442700e914dce7e75e1149d359102f41c48f/app/activity/controllers/activity-controller.js#L20)):*
done

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ushahidi/platform-client/121)*

**Pull request closed without merging**
