### PR TITLE
Sf general settings

### PR DESCRIPTION
**Pull request by Shazeen15**
This pull request makes the following changes:
- I checked the label tags in general settings, roles, and webhooks.
- I fixed the labels and inputs that needed a for/id attributes 

Testing checklist:
- [ ]

- [x] I certify that I ran my checklist

Fixes ushahidi/platform# .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by Shazeen15** [comment]
> Hey @Shazeen15,
> thank you for your Pull Request.
> 
> It looks like you haven't signed our **C**ontributor **L**icense **A**greement, yet.
> 
> > The purpose of a CLA is to ensure that the guardian of a project's outputs has the necessary ownership or grants of rights over all contributions to allow them to distribute under the chosen licence.
> > [Wikipedia](http://en.wikipedia.org/wiki/Contributor_License_Agreement)
> 
> You can read and sign our full Contributor License Agreement [here](https://docs.google.com/forms/d/15LyeKTOP36T5u3290o4hsmqv79v-m_s2QSmgMJXpYp8/viewform).
> 
> Once you've signed reply with `[clabot:check]` to prove it.
> 
> Appreciation of efforts,
> 
> clabot

[clabot:check]

**Review by Angamanga — APPROVED** [review]
Looks good! Thank you for your contribution 🎉

**Comment by Angamanga** [comment]
@Obadha2 Ready for QA. Needs a smoketest for the views Settings->General, Settings->Roles and Settings->Webhooks.

**Comment by tuxpiper** [comment]
Folks, this was merged but without a comment on QA outcome.

Also, does this fix any particular issue that we have logged?

**Pull request merged**
