### PR TITLE
Re-organise app/common module into sub-modules

### PR DESCRIPTION
**Pull request by rjmackay**
This pull request makes the following changes:
- Move auth services etc into common/auth
- Start using thing.type.js naming convention
- Use subdirectories within common module

Test these changes by:
- Check app builds

Ping @willdoran @jasonmule

---
This change is [Reviewable](https://reviewable.io/reviews/ushahidi/platform-client/197)

### CODE REVIEW

**Comment by rjmackay** [comment]
@willdoran @jasonmule what do you think? would this make things clearer? ..

**Comment by willdoran** [comment]
Yeah, I like it alot. I want to split the settings dir into categories, sets etc. I did it for users under the filter system. 

I think as much as possible we should make the dirs a readable path through the app.

**Comment by rjmackay** [comment]
Not really sure what to do with the remaining components that are still in services/directives/etc
One or two could go into a `layout` folder. The rest don't follow much of a theme.

**Comment by rjmackay** [comment]
I'm going to abandon this - I've rearranged the auth code in my register PR - other changes can happen as needed.

**Pull request closed without merging**
