### PR TITLE
fix(posts-form): Fixes default number field

### PR DESCRIPTION
**Pull request by AngadSethi**
This pull request makes the following changes:
- If a default value is submitted in decimal field, it now shows the entire decimal, instead of just the integral part.

Testing checklist:
- [ ] Add a 'decimal' input field to a survey.
- [ ] Specify a default decimal value like '5.64'
- [ ] Add a response. The field now shows '5.64' instead of just '5'
- [x] I certify that I ran my checklist

Fixes ushahidi/platform#3954

### CODE REVIEW

**Review by rowasc — APPROVED** [review]

**Comment by rowasc** [comment]
@Obadha2 please test. 
@AngadSethi THanks!

**Comment by Obadha2** [comment]
@AngadSethi this fails QA. 

- Where there's a default decimal value, only the integral part is shown in edit mode. When looking at responses, the default decimal value is seen as 4.0000
See attached screenshot:
Screen Shot 2020-10-28 at 11 59 16 AM

**Comment by AngadSethi** [comment]
@Obadha2 Thank you for the review! I have corrected both errors.

- Removes the trailing decimals from the view of a post by parsing them before rendering.
- Replaces `parseInt` with `parseFloat` in the posts edit/create form.

I have committed the changes to this branch. Should I open another pull request?

**Comment by Obadha2** [comment]
> @Obadha2 Thank you for the review! I have corrected both errors.
> 
> * Removes the trailing decimals from the view of a post by parsing them before rendering.
> * Replaces `parseInt` with `parseFloat` in the posts edit/create form.
> 
> I have committed the changes to this branch. Should I open another pull request?

@AngadSethi yes, go ahead and open another PR. 

Thanks.

**Comment by AngadSethi** [comment]
@Obadha2 Here it is: https://github.com/ushahidi/platform-client/pull/1608

**Pull request merged**
