### PR TITLE
fixed issue #2383 dual dropdowns

### PR DESCRIPTION
**Pull request by c3ho**
This pull request makes the following changes:
- removed dual dropdown when selecting languages
- removed toggle for first language selection option and svg

Testing checklist:
- [x] verified I could still reach and see second dropdown, first drop down toggle id now disabled

- [x] I certify that I ran my checklist

Fixes ushahidi/platform# .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by c3ho** [comment]
[clabot:check]

**Comment by rowasc** [comment]
FYI @Angamanga this passed just fine locally, so I'm sending it to @Obadha2 in the test environment for a testing round with multiple languages.

**Comment by rowasc** [comment]
@allcontributors add c3ho for code

**Comment by Obadha2** [comment]
@rowasc this passes qa on test environment. :+1:

**Pull request merged**
