### PR TITLE
Fixed cannot unselect post

### PR DESCRIPTION
**Pull request by OluyemisiA**
This pull request makes the following changes:

- makes it possible to unselect a post in the data-view

Testing checklist:

- [x] Select a post in data-view

- [x] Click on it again

- [x] It should move back into original position and no post should be shown to the right

- [x] I certify that I ran my checklist

Fixes ushahidi/platform#2238.

Ping @ushahidi/platform

### CODE REVIEW

**Comment by OluyemisiA** [comment]
> [clabot:check]

[clabot:check]

**Comment by OluyemisiA** [comment]
Hello @Angamanga @rowasc Please take a look.
Thank you

**Review by Angamanga — APPROVED** [review]
Works fine! Thank you for your contribution!

**Comment by Angamanga** [comment]
@Obadha2 Ready for QA! 🌮

**Comment by Obadha2** [comment]
QA'd, passes. 👍

**Pull request merged**
