### PR TITLE
Fix: Removing warning in posts about duplicate options

### PR DESCRIPTION
**Pull request by Angamanga**
This pull request makes the following changes:
- Removes warning about duplicate options in post, but keeps the check when adding a new attribute (this makes the warning in the post redundant, it should not be possible to add duplicates in the first place)

Testing checklist:
- [ ] Go to surveys-> add new checkbox, radio-button or select
- [ ] Try adding duplicate options, it should not be possible
- [ ] In a survey with already present duplicate options (Anna will add one of those surveys to staging), try adding a post
- [ ] You will see an error-message warning about duplicate options at each field with problems
- [ ] Go back to settings and remove the duplicate options
- [ ] Go back to add a post, no warnings visible.

- [ ] I certify that I ran my checklist

Fixes ushahidi/platform# .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by rowasc** [comment]
@Angamanga I think the warning was about fixing pre-broken forms basically? Warning the admin about it?

**Comment by Angamanga** [comment]
@rowasc Good point! Added back the check but only checking the concerned fields!

**Review by rowasc — APPROVED** [review]
nice

**Comment by Angamanga** [comment]
@Obadha2 Ready for review 🎉

**Comment by Obadha2** [comment]
QA'd, passed. 👍

**Pull request merged**
