### PR TITLE
#4100 - Change the alt-text on the user-avatar

### PR DESCRIPTION
**Pull request by Sunairaa**
This pull request makes the following changes:

- Change the alt text of the avatar.
- Change the text of <span> - tooltip with account-setting which needs to be translated. 

Testing checklist:
- [x] Alt text is showing with profile-settings.

- [x] Tooltip was showing username now it is showing with profile setting label.

- [x] I certify that I ran my checklist

Fixes ushahidi/platform# .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by Sunairaa** [comment]
Hey, @Angamanga and @rowasc kindly review my work.

**Comment by Sunairaa** [comment]
Hey

**Comment by Sunairaa** [comment]
while doing this task i found some UI issues: 

1. logo text is breaking (not shown completely) on my screen.
image

2. language dropdown options text was not visible when I select particular language like currently there is only English option so when I hover on so I can see text otherwise text was not visible.
image
image

can I be assigned to fix these issues?

**Comment by Sunairaa** [comment]
I also saw another issue I was not able to test my code on other locales then I noticed in language.json was not loading.

**Comment by Angamanga** [comment]
@Sunairaa Thank you! I will review shortly!

**Review by Angamanga — APPROVED** [review]
Thank you for your contribution! This works fine!

**Comment by Angamanga** [comment]
@Obadha2 Ready for QA 🎉

**Comment by Sunairaa** [comment]
> Thank you for your contribution! This works fine!

You're welcome @Angamanga , would love to contribute more 👍

**Comment by Obadha2** [comment]
QA'd, passes. 👍

**Pull request merged**
