### PR TITLE
Add role button to improve accessibility in app/main files #4113

### PR DESCRIPTION
**Pull request by muchirijane**
This pull request makes the following changes:
- It added a role button to every button in the app/main files. 

Testing checklist:
- [ ]

- [x] I certify that I ran my checklist

Fixes ushahidi/platform# .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by renujain31** [comment]
Hey @muchirijane! you don't need to add the role="button" in elements which are specified by the <button> tag. You just need to add them where they aren't in <button> element. For example here: https://github.com/ushahidi/platform-client/blob/develop/app/main/posts/detail/post-messages.html#L38 Also, it would be great if you can add "tabindex=0" in those elements to enable keyboard navigation.

**Comment by muchirijane** [comment]
Noted. I will change the code. 💯

**Review by rowasc — CHANGES_REQUESTED** [review]
Hey. Thanks for your contribution. Marking as "changes requested" due to @renujain31's review (otherwise I end up checking the same PRs twice). 
Another bit of feedback: please add a test checklist, and a link to the issue this is addressing. Thanks!
Looking forward to the changes!

**Comment by muchirijane** [comment]
Hey @rowasc, I went back and did it all again and created another PR => https://github.com/ushahidi/platform-client/pull/1582
We can close this one.

**Comment by rowasc** [comment]
@muchirijane I'll do that (close) this time,  but as a general rule please don't create new pull requests when we send feedback, since it just adds clutter and complicates knowing what's been done before/what the reviewers have said/etc. It's been happening to a lot of folks, it's not a big deal just a thing to keep in mind!

Thanks!

**Comment by muchirijane** [comment]
@rowasc Noted, Thanks.

**Pull request closed without merging**
