### PR TITLE
#4102 Add alt to deployment logo 

### PR DESCRIPTION
**Pull request by Somaru-chan**
As requested in the following issue: https://github.com/ushahidi/platform/issues/4102

This pull request makes the following changes:
- Adds alt text to deployment logo in these five files:
  - `../activity/activity.html`
  - `../views/mode-context.html`
  - `../views/post-view-data.html`
  - `../settings/settings-list.html`
  - `../site/settings-editor.html`

Testing checklist:
- [ ] Open the client platform 
- [ ] Login with role "Admin" to unlock settings
- [ ] Navigate to Settings > General, then browse and upload a deployment logo 
- [ ] Notice there is a text that reads "Deployment-logo" when you hover over the deployment logo.

- [x] I certify that I ran my checklist

Fixes ushahidi/platform# .

Ping @ushahidi/platform

### CODE REVIEW

**Review by rowasc — CHANGES_REQUESTED** [review]
I'm not sure I agree with calling out "Deployment logo" without a way for deployers to specify something about the logo that actually helps people understand the logo. @Angamanga thoughts? 

@Somaru-chan can you link to the corresponding ticket ? Every PR should be linked to a ticket.

**Comment by Somaru-chan** [comment]
> I'm not sure I agree with calling out "Deployment logo" without a way for deployers to specify something about the logo that actually helps people understand the logo. @Angamanga thoughts?
> 
> @Somaru-chan can you link to the corresponding ticket ? Every PR should be linked to a ticket.

Sorry, I thought I've added it. Linked now.

**Comment by Angamanga** [comment]
@rowasc I think of it as the first step of improving accessibility. The next step would be to add a way for deployers to specify an alt-text to their deployment logos and also for users to add alt-texts to their uploaded images. I haven't added those issues yet.

**Comment by Somaru-chan** [comment]
> @rowasc I think of it as the first step of improving accessibility. The next step would be to add a way for deployers to specify an alt-text to their deployment logos and also for users to add alt-texts to their uploaded images. I haven't added those issues yet.

@Angamanga Hi there. It says changes are requested for this PR before it's approved, but I'm not sure what exactly needs to be changed. Can you please point it out for me?

**Review by Angamanga — APPROVED** [review]
Thank you for your contribution! Approved!

**Comment by Angamanga** [comment]
@Obadha2 Ready for QA.

**Comment by Obadha2** [comment]
QA'd, passes. 👍

**Pull request merged**
