### PR TITLE
Made share button and menu accessible with keyboard

### PR DESCRIPTION
**Pull request by renujain31**
This pull request makes the following changes:
- It makes the share button accessible 
- It makes the export filtered data option present in share menu accessible 

Testing checklist:
- [ ] Open /views/maps.
- [ ] Disconnect your mouse and navigate with keyboard only.
- [ ] Go to the share menu and press enter
- [ ] The export filtered data shall be accessible with keyboard

- [x] I certify that I ran my checklist

Recording:

Export filtered data

Fixes ushahidi/platform#4189

### CODE REVIEW

**Review by Angamanga — APPROVED** [review]
Works fine 🎉

**Comment by Angamanga** [comment]
@Angamanga To merge once modals-acc is merged to develop/v5-main.

**Comment by Angamanga** [comment]
@Obadha2 This is ready for QA 🎉

**Comment by Obadha2** [comment]
QA'd, passes. 👍

**Pull request merged**
