### PR TITLE
Mustang/post edit

### PR DESCRIPTION
**Pull request by willdoran**
This pull request makes the following changes:
- Changed Post edit/create controllers to expect form
- Change stages to be vertical tabs
- Changed post status to merely set status rather than forcing update
- Changed user interface
- Added date time directive

Test these changes by:
- Try it out
- Known issue: awaiting time picker css from PL

Fixes ushahidi/platform#1054

Ping @ushahidi/platform

---
This change is [Reviewable](https://reviewable.io/reviews/ushahidi/platform-client/208)

### CODE REVIEW

**Comment by rjmackay** [comment]
Looking fairly good so far - I haven't dug into the detail since most of that is copy/paste from previously.

<details><summary><i>Previously, coveralls wrote…</i></summary>
> 
> [Coverage Status](https://coveralls.io/builds/6423958)
> 
> Coverage decreased (-0.03%) to 56.582% when pulling **3041403c1a7feafda23d627730199444640a78be on mustang/post-edit** into **f35e0ff670b87216afa527795e9482334ed7b4e4 on develop**.
> 
</details>


---

Reviewed 13 of 26 files at r1, 5 of 8 files at r2, 6 of 9 files at r4, 4 of 6 files at r5, 2 of 5 files at r6, 6 of 12 files at r7.
Review status: 33 of 38 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[app/common/common-module.js, line 92 \[r7\]](https://reviewable.io:443/reviews/ushahidi/platform-client/208#-KJEC4mAtGfIUD-cmOxv:-KJEC4mAtGfIUD-cmOxw:864345982) ([raw file](https://github.com/ushahidi/platform-client/blob/3041403c1a7feafda23d627730199444640a78be/app/common/common-module.js#L92)):*
> ```JavaScript
> 
> // Load submodules
> require('./directives/adaptive-input.js');
> ```

Could we create this in the standard format above instead? its what we use more often..

---

*[app/common/directives/adaptive-input.js, line 46 \[r7\]](https://reviewable.io:443/reviews/ushahidi/platform-client/208#-KJECQyHxKPyvn6y8Caf:-KJECQyHxKPyvn6y8Cag:651291848) ([raw file](https://github.com/ushahidi/platform-client/blob/3041403c1a7feafda23d627730199444640a78be/app/common/directives/adaptive-input.js#L46)):*
> ```JavaScript
> 
>             function focusOn($event) {
>                 $event.preventDefault();
> ```

Do you really need to preventDefault for focus and blur events?? that seems like a bad idea

---

*[app/post/post-module.js, line 19 \[r7\]](https://reviewable.io:443/reviews/ushahidi/platform-client/208#-KJECtaDlUobPmxf_RUv:-KJECtaEdys6GpqmfhsR:1744482525) ([raw file](https://github.com/ushahidi/platform-client/blob/3041403c1a7feafda23d627730199444640a78be/app/post/post-module.js#L19)):*
> ```JavaScript
> .directive('postValueEdit', require('./directives/post-value-edit.directive.js'))
> .directive('postStatus', require('./directives/post-status.directive.js'))
> .directive('postVerticalTabs', require('./directives/post-vertical-tabs.directive.js'))
> ```

.. but the tabs are now horizontal? shouldn't this just be post-tabs or similar?

---

*[app/post/post-routes.js, line 16 \[r7\]](https://reviewable.io:443/reviews/ushahidi/platform-client/208#-KJEDIBoBimOweSc-fA1:-KJEDIBpoBBPMj-kWyKo:262288780) ([raw file](https://github.com/ushahidi/platform-client/blob/3041403c1a7feafda23d627730199444640a78be/app/post/post-routes.js#L16)):*
> ```JavaScript
>         templateUrl: 'templates/posts/modify/modify.html',
>         resolve: {
>             form: ['$route', 'FormEndpoint', function ($route, FormEndpoint) {
> ```

This could probably happen in activate() instead. https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#style-y081

What do you think? We could cancel routing if the form doesn't exist, but its unlikely and we can do that same this with a redirect to `/`

---

*[app/post/post-routes.js, line 41 \[r7\]](https://reviewable.io:443/reviews/ushahidi/platform-client/208#-KJEDV8TvV-S3bopgLzr:-KJEDV8Uo1M1aiJzy9Nb:90102873) ([raw file](https://github.com/ushahidi/platform-client/blob/3041403c1a7feafda23d627730199444640a78be/app/post/post-routes.js#L41)):*
> ```JavaScript
>     .when('/posts/:id/edit', {
>         controller: require('./controllers/post-edit-controller.js'),
>         templateUrl: 'templates/posts/modify/modify.html',
> ```

Do you think we should prefer modify/modify or modify/main in general? I've done views/main elsewhere but that case was super unclear if I did views/views.. 

---

*[app/post/controllers/post-edit-controller.js, line 35 \[r7\]](https://reviewable.io:443/reviews/ushahidi/platform-client/208#-KJEDlxIWs_hBFlvkaD1:-KJEDlxIWs_hBFlvkaD2:-1330617800) ([raw file](https://github.com/ushahidi/platform-client/blob/3041403c1a7feafda23d627730199444640a78be/app/post/controllers/post-edit-controller.js#L35)):*
> ```JavaScript
> 
>     if (post.form) {
>         $scope.form = FormEndpoint.get({ id: post.form.id }, function (form) {
> ```

I think post edit and create are actually more consistent if we keep the FormLoading in the controller (vs in route resolve)

---

*[app/post/directives/post-value-edit.directive.js, line 49 \[r7\]](https://reviewable.io:443/reviews/ushahidi/platform-client/208#-KJEEMAk-UOJWAk8qLhD:-KJEEMAk-UOJWAk8qLhE:2135371118) ([raw file](https://github.com/ushahidi/platform-client/blob/3041403c1a7feafda23d627730199444640a78be/app/post/directives/post-value-edit.directive.js#L49)):*
> ```JavaScript
>     }
> 
>     function isDate(attr) {
> ```

I think these could all be handled better with a simple ng-switch in the template? the many function is overkill

---

*[server/www/templates/posts/modify.html, line 2 \[r7\]](https://reviewable.io:443/reviews/ushahidi/platform-client/208#-KJEF1BqfBj5HUZJ1rfZ:-KJEF1BqfBj5HUZJ1rf_:1599711769) ([raw file](https://github.com/ushahidi/platform-client/blob/f35e0ff670b87216afa527795e9482334ed7b4e4/server/www/templates/posts/modify.html#L2)):*
> ```HTML
> <main class="page-content layout-c" role="main">
>     <post-choose-form post="post" ng-if="! post.form.id" active-form="activeForm"></post-choose-form>
> ```

This is the one place post-choose-form still exists: when a post in the system (ie. SMS) doesn't have a form id.. we need a UI to choose post type.

---

*[server/www/templates/posts/post-datetime.html, line 9 \[r7\]](https://reviewable.io:443/reviews/ushahidi/platform-client/208#-KJEEqXepfVVib23rABp:-KJEEqXepfVVib23rABq:-1899265516) ([raw file](https://github.com/ushahidi/platform-client/blob/3041403c1a7feafda23d627730199444640a78be/server/www/templates/posts/post-datetime.html#L9)):*
> ```HTML
>         type="date"
>         pick-a-date="date"
>         pick-a-date-options="{ format: 'yyyy-mm-dd' }"
> ```

options needs to be a variable on scope - otherwise the console fills with errors. :(

---

*[server/www/templates/posts/modify/post-vertical-tabs.html, line 2 \[r7\]](https://reviewable.io:443/reviews/ushahidi/platform-client/208#-KJEFJBcS4Pv5nuk_WKD:-KJEFJBdKKUHVqerJNKE:-1971883594) ([raw file](https://github.com/ushahidi/platform-client/blob/3041403c1a7feafda23d627730199444640a78be/server/www/templates/posts/modify/post-vertical-tabs.html#L2)):*
> ```HTML
> <div>
>     <nav class="tabs-menu init" data-tabs="tabs-tasks" data-tabs-hash="">
> ```

Could we hide this entirely in cases where theres only a single stage?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ushahidi/platform-client/208#-:-KJEFX73Dt_vyGHKdRqo:598569748)*

**Comment by willdoran** [comment]
Review status: 33 of 38 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[app/common/common-module.js, line 92 \[r7\]](https://reviewable.io:443/reviews/ushahidi/platform-client/208#-KJEC4mAtGfIUD-cmOxv:-KJNN5DDX_Kuevd4Pwc7:180337500) ([raw file](https://github.com/ushahidi/platform-client/blob/3041403c1a7feafda23d627730199444640a78be/app/common/common-module.js#L92)):*
<details><summary><i>Previously, rjmackay (Robbie Mackay) wrote…</i></summary>
> Could we create this in the standard format above instead? its what we use more often..
</details>
Yep, I was following the form for dropdown and accordion but I'll change to the other!

---

*[app/common/directives/adaptive-input.js, line 46 \[r7\]](https://reviewable.io:443/reviews/ushahidi/platform-client/208#-KJECQyHxKPyvn6y8Caf:-KJNN2wkcgxt7MUUKnEp:-2142252934) ([raw file](https://github.com/ushahidi/platform-client/blob/3041403c1a7feafda23d627730199444640a78be/app/common/directives/adaptive-input.js#L46)):*
<details><summary><i>Previously, rjmackay (Robbie Mackay) wrote…</i></summary>
> Do you really need to preventDefault for focus and blur events?? that seems like a bad idea
</details>
I wanted to prevent the default for the captured element but not the bubbling effect. So I wanted this element to behave according to how the bind I dictated executes but not interfere with elements above it.

Because we're really only using bind in this case and we don't mix in jQuery it's kind of academic since nothing else is likely to capture from this element.

I went back and forth about using it or not using it because it doesn't make a difference now BUT if something else binds or if we add jQuery that could change.

So I'm really not sure, removing it will mean that if anything is ever bound to this element there could be a conflict. Leaving it means that if anything is ever bound to this element there could be a conflict.

Having typed all that, i think it's probably a non-issue that if we do start using jquery or capturing events all around the place we'll have to handle it appropriately at that point.

---

*[app/post/post-module.js, line 19 \[r7\]](https://reviewable.io:443/reviews/ushahidi/platform-client/208#-KJECtaDlUobPmxf_RUv:-KJNEa6cXybvu0spOSY-:-1980254030) ([raw file](https://github.com/ushahidi/platform-client/blob/3041403c1a7feafda23d627730199444640a78be/app/post/post-module.js#L19)):*
<details><summary><i>Previously, rjmackay (Robbie Mackay) wrote…</i></summary>
> .. but the tabs are now horizontal? shouldn't this just be post-tabs or similar?
</details>
I thought the tabs were now vertical...but post-tabs is a simpler naming scheme, their spatial orientation is not hugely important.

---

*[app/post/post-routes.js, line 16 \[r7\]](https://reviewable.io:443/reviews/ushahidi/platform-client/208#-KJEDIBoBimOweSc-fA1:-KJNF94gE0y0IFu_X8m6:-1622272391) ([raw file](https://github.com/ushahidi/platform-client/blob/3041403c1a7feafda23d627730199444640a78be/app/post/post-routes.js#L16)):*
<details><summary><i>Previously, rjmackay (Robbie Mackay) wrote…</i></summary>
> This could probably happen in activate() instead. https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#style-y081
> 
> What do you think? We could cancel routing if the form doesn't exist, but its unlikely and we can do that same this with a redirect to `/`
</details>
In some of the other controllers I've started moving loading into activate and I think it does make more sense. Adding to routing complicates the path I think. I'll move this one.

---

*[app/post/post-routes.js, line 41 \[r7\]](https://reviewable.io:443/reviews/ushahidi/platform-client/208#-KJEDV8TvV-S3bopgLzr:-KJNEry6TGYRyvVRYQvU:2118485535) ([raw file](https://github.com/ushahidi/platform-client/blob/3041403c1a7feafda23d627730199444640a78be/app/post/post-routes.js#L41)):*
<details><summary><i>Previously, rjmackay (Robbie Mackay) wrote…</i></summary>
> Do you think we should prefer modify/modify or modify/main in general? I've done views/main elsewhere but that case was super unclear if I did views/views.. 
</details>
I would prefer modify/modify but perhaps main is more normalising though, I'll switch it.

---

*[app/post/controllers/post-edit-controller.js, line 35 \[r7\]](https://reviewable.io:443/reviews/ushahidi/platform-client/208#-KJEDlxIWs_hBFlvkaD1:-KJNNDCFsre32zh4XUzq:746777961) ([raw file](https://github.com/ushahidi/platform-client/blob/3041403c1a7feafda23d627730199444640a78be/app/post/controllers/post-edit-controller.js#L35)):*
<details><summary><i>Previously, rjmackay (Robbie Mackay) wrote…</i></summary>
> I think post edit and create are actually more consistent if we keep the FormLoading in the controller (vs in route resolve)
</details>
Cool, as with above I'll move it

---

*[app/post/directives/post-value-edit.directive.js, line 49 \[r7\]](https://reviewable.io:443/reviews/ushahidi/platform-client/208#-KJEEMAk-UOJWAk8qLhD:-KJNNHS7DywSULlRsZyK:-337917515) ([raw file](https://github.com/ushahidi/platform-client/blob/3041403c1a7feafda23d627730199444640a78be/app/post/directives/post-value-edit.directive.js#L49)):*
<details><summary><i>Previously, rjmackay (Robbie Mackay) wrote…</i></summary>
> I think these could all be handled better with a simple ng-switch in the template? the many function is overkill
</details>
Yeah, it's a little odd looking given that all it does is check an attribute directly available in the template. I ported it straight over, but there are actually quite a lot of checks for things like date/datetime and checkbox.

For example, it determines which classes should be added to the label form-field. So what I've done for now is reduce the functions to only those that appear more than once.

---

*[server/www/templates/posts/modify.html, line 2 \[r7\]](https://reviewable.io:443/reviews/ushahidi/platform-client/208#-KJEF1BqfBj5HUZJ1rfZ:-KJNNXCT-tfsMtMChMae:-412939388) ([raw file](https://github.com/ushahidi/platform-client/blob/f35e0ff670b87216afa527795e9482334ed7b4e4/server/www/templates/posts/modify.html#L2)):*
<details><summary><i>Previously, rjmackay (Robbie Mackay) wrote…</i></summary>
> This is the one place post-choose-form still exists: when a post in the system (ie. SMS) doesn't have a form id.. we need a UI to choose post type.
</details>
Ah - I'll check the PL in case I missed something that already does that.

---

*[server/www/templates/posts/post-datetime.html, line 9 \[r7\]](https://reviewable.io:443/reviews/ushahidi/platform-client/208#-KJEEqXepfVVib23rABp:-KJNNj7dTHHkX_E0gYoN:-298460980) ([raw file](https://github.com/ushahidi/platform-client/blob/3041403c1a7feafda23d627730199444640a78be/server/www/templates/posts/post-datetime.html#L9)):*
<details><summary><i>Previously, rjmackay (Robbie Mackay) wrote…</i></summary>
> options needs to be a variable on scope - otherwise the console fills with errors. :(
</details>
Really? I'm not getting that. That's super weird. What browser are you seeing it on?

---

*[server/www/templates/posts/modify/post-vertical-tabs.html, line 2 \[r7\]](https://reviewable.io:443/reviews/ushahidi/platform-client/208#-KJEFJBcS4Pv5nuk_WKD:-KJNNpOklwReo0cL0VwD:160424895) ([raw file](https://github.com/ushahidi/platform-client/blob/3041403c1a7feafda23d627730199444640a78be/server/www/templates/posts/modify/post-vertical-tabs.html#L2)):*
<details><summary><i>Previously, rjmackay (Robbie Mackay) wrote…</i></summary>
> Could we hide this entirely in cases where theres only a single stage?
</details>
yep

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ushahidi/platform-client/208)*

**Comment by willdoran** [comment]
I've made most of the changes but I need to test them out and investigate, the datepicker error and the modify for sms

<details><summary><i>Previously, rjmackay (Robbie Mackay) wrote…</i></summary>
> Looking fairly good so far - I haven't dug into the detail since most of that is copy/paste from previously.
</details>


---

Review status: 33 of 38 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ushahidi/platform-client/208#-:-KJWFOQMOGM-aK_HnXsy:-660326235)*

**Comment by rjmackay** [comment]
A few minor comments but this looks good to me

<details><summary><i>Previously, coveralls wrote…</i></summary>
> 
> [Coverage Status](https://coveralls.io/builds/6487538)
> 
> Coverage decreased (-1.5%) to 54.815% when pulling **a43a28bfac112c7e3818e6414c99c4d5b7be1b1b on mustang/post-edit** into **ecb634625381f95f6bf8c902335ebd454f23f52c on develop**.
> 
</details>


---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ushahidi/platform-client/208#-:-KJccNXjyA_DVNYtpLoU:-1425813132)*

**Pull request merged**
