### PR TITLE
Make filter actions bar opaque to make text readable.

### PR DESCRIPTION
**Pull request by noone0212**
This pull request makes the following changes:
- Made filter actions bar 100% opaque to make the text behind readable.

Testing checklist:
- [ ]

- [ ] I certify that I ran my checklist

Fixes ushahidi/platform#2374 .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by noone0212** [comment]
clabot:check

**Comment by Erioldoesdesign** [comment]
@noone0212 Can I see a screenshot of the new 100% opacity buttons please? I want to check the visuals :)

**Comment by noone0212** [comment]
Hi @Erioldoesdesign ! 
I had to close this pull request #1436 due to some faults. But I corrected the faults and made again  pull request #1437.
Here's the screenshot of the visuals 
Screenshot from 2020-02-27 17-09-05

**Comment by Erioldoesdesign** [comment]
Awesome! 

This is good to go but if you felt like adding a little drop shadow to the light grey button like how the yellow button looks I'd very much encourage that :D

**Pull request closed without merging**
