### PR TITLE
Fix - Secondary toolbar and add-post-button look untidy while editing post.

### PR DESCRIPTION
**Pull request by noone0212**
This pull request makes the following changes:
- Hiding add-post-button while editing the post.

Testing checklist:
  - Login into the deployment.
  - Go to Data.
  - Select any post to edit.
  - Scroll down to end of page, previously add-post-button and secondary toolbar looked untidy.
  - Now, while editing post add-post-button is removed completely.
  - Saving or cancelling the action bring the button back to its original position.

- [x] I certify that I ran my checklist

Fixes ushahidi/platform#3905 .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by noone0212** [comment]
After Disabling:

Screenshot from 2020-03-31 13-38-06

**Comment by Erioldoesdesign** [comment]
From a design pov I don't think this is the best visualisation of a 'disabled' add post button. It's more distracting and users might be 'Why is this transparent floating button here? is it an error?' is my machine broken? the better thing from my pov is to remove it/make fully transparent and have it come back once the click cancel or save. or hide it completely behind the modal. 

This semi-transparent low opacity is confusing I think!

**Comment by noone0212** [comment]
Screenshot from 2020-03-31 18-05-33
Please review this.

**Comment by Erioldoesdesign** [comment]
Would definitely want @Angamanga @rowasc and the wider team to be ok with this as I don't have authority to review and clear this kind of amend

**Comment by Angamanga** [comment]
@noone0212 The best option would be to completely remove the button while editing, we are trying to remove disabled buttons as best as we can. You could try a ng-show instead 👍

**Comment by noone0212** [comment]
I have removed it completely. Please see https://github.com/ushahidi/platform-client/pull/1479/commits/dcbe4516df0221b0d63e3f10c607899b14cd7519.

**Comment by Angamanga** [comment]
@noone0212 Thank you! Could you also add a testing-checklist to this pr? The steps to do in order to check if this works? That helps our QA-process! 🎉

**Comment by rowasc** [comment]
@Obadha2 was this tested? If not, can you test it in the morning? Thanks !

**Comment by Obadha2** [comment]
@rowasc this was looked at [here](https://github.com/ushahidi/platform/issues/3905#event-3214465020)

**Pull request merged**
