### PR TITLE
Jumping Map View

### PR DESCRIPTION
**Pull request by webong**
This pull request makes the following changes:
- Modify the `addPostsToMap` function to accepts a boolean parameter that determines if the status of the received posts
- Avoid looping over geojson layers using the `cluster.addLayers` to set layers to the cluster group

Test this by:
- [ ] The map loads to show all the markers loaded into it, no markers are left outside of the initial view after it finishes loading.
- [ ] When the map has more than 400 points , the view auto-adjusts progressively as points are loaded into it, but it doesn't feel like it's "shaking" or "jumping"

Fixes ushahidi/platform#2265.

Ping @ushahidi/platform

### CODE REVIEW

**Review by Ifycode — COMMENTED** [review]
Works nice @webong 👍🏽

**Comment by tuxpiper** [comment]
I think it needs another look 😬   I commented in Slack: https://ushahidi.slack.com/archives/CFC4WQG4V/p1659540157443289

**Review by tuxpiper — APPROVED** [review]
Ah yes, it was actually so simple :)

**Comment by tuxpiper** [comment]
@AmTryingMyBest this is ready for QA

**Pull request merged**
