### PR TITLE
Add button role to improve accessibility in app/settings #4114

### PR DESCRIPTION
**Pull request by onyeepeace**
This pull request makes the following changes:
- Adds button role to improve accessibility

Testing checklist:
- [x] The buttons which are not button elements now act as buttons

- [x] I certify that I ran my checklist

Fixes ushahidi/platform#4114.

Ping @ushahidi/platform

### CODE REVIEW

**Review by renujain31 — APPROVED** [review]
This looks good to me! Thanks @onyeepeace!

**Comment by renujain31** [comment]
@rowasc @Angamanga It would be great if you could also review it once!

**Review by rowasc — APPROVED** [review]
@onyeepeace this is great. Could you add a testing checklist ? Basically the steps for QA to verify each change. Thanks . Once you do that, please tag @Obadha2 for testing.

@Obadha2 this is pre-approved but only once the checklist is added can we merge.

**Comment by Obadha2** [comment]
QA'd, passes. 👍

**Pull request merged**
