### PR TITLE
Move video url validation to PostEditorService and invalidate containing form if validation fails.

### PR DESCRIPTION
**Pull request by brymut**
**This pull request makes the following changes:**
- move video url validation to PostEditService.validateVideoUrl
- use PostEditService.validateVideoUrl to validate url in directive and invalidate form scope when validation fails.
- [test] add PostEditService.validateVideoUrl tests

**Testing checklist:**
- [x] Go to settings and create a survey with an 'embed video' field.
- [x] Fill in a new survey response based on the one created in the previous step, using a random, non-youtube/non-vimeo-url to the video URL field.
- [x] Click save.
- [x] Error notification appears and post is **NOT** saved.
- [x] Edit the video URL field to include a valid youtube/vimeo URL and click save.
- [x] Post saves successfully.

**Quick demo**
demo of working version
apologies if too blurry, I can try to resubmit another screenshot on request.
- [x] I certify that I ran my checklist

Fixes ushahidi/platform#3904 .

Ping @ushahidi/platfrom

### CODE REVIEW

**Comment by brymut** [comment]
[clabot:check]

**Comment by brymut** [comment]
Just a heads up, still working on this.

**Comment by brymut** [comment]
Hi @Angamanga , I've managed to get a possible solution working. Ready for feedback whenever possible. Also, there was some commented out code thumbnail code in the post-video directive that I wasn't sure to remove, should I just leave it for now?

**Comment by Angamanga** [comment]
@brymut This looks good and works fine, super-well done 🎉 . You can absolutely delete the commented out code, thank you for noticing. 

Another thing that would be nice to have, if you have time, is to display an error-label under the field, in case the url does not pass the validation. We have not had that for videos previously, but now we can actually add it. We do this for other fields, you can have a look here https://github.com/ushahidi/platform-client/blob/develop/app/main/posts/modify/post-value-edit.html#L22 for an example how it is done in other places. If you don't have time its totally fine and I'll add it as a new issue :).

Before I approve, @rowasc could you do a double-check as well? Since its one of the gnarliest parts of our code and I might have missed something. 🙏

**Comment by brymut** [comment]
Thanks for having a look @Angamanga 

> @brymut This looks good and works fine, super-well done 🎉 . You can absolutely delete the commented out code, thank you for noticing.

I've amended my last commit to delete the commented out code.


> Another thing that would be nice to have, if you have time, is to display an error-label under the field, in case the url does not pass the validation. We have not had that for videos previously, but now we can actually add it. We do this for other fields, you can have a look here https://github.com/ushahidi/platform-client/blob/develop/app/main/posts/modify/post-value-edit.html#L22 for an example how it is done in other places. If you don't have time its totally fine and I'll add it as a new issue :).

At the moment, I don't quite have enough time for the remainder of the week, however, if you can track that this a new issue could you please tag/ping me and I'll have a try again over the next week.

**Comment by brymut** [comment]
Hi again @Angamanga , just about to continue with adding the error-label you mentioned soon. Should I go on working off this PR or will it be tracked in a separate issue?

**Comment by Angamanga** [comment]
@brymut Sorry for late reply! Yes, please go ahead and add it to this pr since we haven't had time for a second review yet. Thank you so much for working on this 🎉

**Comment by tuxpiper** [comment]
@Angamanga  could you please take another quick look and consider for merging again?

**Comment by brymut** [comment]
Hi @tuxpiper, sorry I’ve taken so long on updating this PR as I agreed to. May I have one more week?

**Comment by tuxpiper** [comment]
no problem @brymut  , will check back next week. Thank you!

**Comment by brymut** [comment]
Got some progress done with this over the weekend will push by end of day

**Comment by brymut** [comment]
Okay, so I got a little stuck today and changes started to get messy, so I restarted a new solution that I think should be alright without requiring big edits to the directives involved.

ezgif com-video-to-gif (3)

**Comment by tuxpiper** [comment]
hi @brymut!  is this ready for review?

**Comment by brymut** [comment]
hi @tuxpiper , sorry I should have been more explicit in my previous comment. Yes, please review.

**Comment by tuxpiper** [comment]
np @brymut 👌 thanks!

@Angamanga could you please take a look?

**Comment by rowasc** [comment]
@Angamanga just bumping this in case it got lost :sweat_smile: Thanks!

**Comment by rowasc** [comment]
@Angamanga hey just bumping this one (I know you're busy, just making sure it doesn't get lost ) . Thanks !

**Review by Angamanga — APPROVED** [review]
This works fine now! Thank you @brymut for your contribution! 🎉

**Comment by Angamanga** [comment]
@rowasc Reviewed and approved 👍

**Comment by rowasc** [comment]
@Obadha2 this can be merged and tested in steve as soon as you're ready

**Comment by Obadha2** [comment]
QA'd, passes. :+1:

**Pull request merged**
