### PR TITLE
Fix: Adding timezone to correct changes in date/date-time-fields

### PR DESCRIPTION
**Pull request by Angamanga**
This pull request makes the following changes:
- Adds timezone-information to date and date/time fields with
  - required fields
  - default values
  - fields that are not required and does not have a default value, when a value is added by the user
- Changes timezone-information in edit-view when the user change the value in date/date-time field only

Testing checklist:
- Add a post with date and date/time fields:
 1. required field
 2. with default values
 3. fields that are not required and does not have a default value

Check the values sent to the api. 
- [ ] All times when a value is given in the field, either if it is pre-filled or if it is changed/added by the user, this addition should be added to the value-object: `{value_meta: { from_tz: "timezone info}}`

Change the timezone on your computer
Edit the post
- [ ] the value_meta should update to current timezone

- [ ] I certify that I ran my checklist

Fixes ushahidi/platform# .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by Angamanga** [comment]
@tuxpiper @webong Hopefully the last fix for date-times. I added QA by dev since it requires checking the network-tab.

**Comment by Angamanga** [comment]
@tuxpiper @webong  Could one of you review please?

**Review by tuxpiper — APPROVED** [review]
This looks good to me :+1: I will merge and QA

**Comment by tuxpiper** [comment]
QA'ed successfully and deployed

**Pull request merged**
