### PR TITLE
2091 - fixes saved search dropdown not visible when there are saved searches available

### PR DESCRIPTION
**Pull request by rowasc**
This pull request makes the following changes:
- adds a scope var with length of searchs calculated by keys, since we are switching an array to an object length was not changing when we go the data.

Testing checklist:
- [x] Logged out: verify that you don't see saved searches 
- [x] Logged in, with saved searches available to your user: verify that you see a dropdown with saved searches
- [x] Logged in, select a saved search and check that the filter is applied in the bug icons. 

Fixes ushahidi/platform# .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by willdoran** [comment]
@rowsac When clicking the * beside the search box, I see a modal not a dropdown, is that correct?

**Comment by rowasc** [comment]
@willdoran the star icon is back to the old feature of the modal with saved search listed, so that's OK . This fix involved fixing the dropdown/select box in the filters dropdown.

**Comment by rowasc** [comment]
screen shot 2017-10-11 at 10 24 34 am
Fix involves this. 
Modal is correct on star icon

**Comment by willdoran** [comment]
@rowasc is this behaviour correct:
1. Click on Savedsearch from the * modal
2. In filters box see all filters:
screen shot 2017-10-11 at 09 26 30

1. Click on Savedsearch from savedsearch drop down with in filters
2. See only the filter bug element Savedsearch: <savedsearch_id>
screen shot 2017-10-11 at 09 26 59

**Comment by willdoran** [comment]
Combining both steps creates this set of filter tags
screen shot 2017-10-11 at 09 28 41

The filtering appears correct, and this may have been an existing behaviour

**Pull request merged**
