### PR TITLE
Improvements to map/timeline contextual sidebar

### PR DESCRIPTION
**Pull request by rjmackay**
- Move active filters above survey filters (ushahidi/platform#1252)
- Add 'Create new survey' button to mode context (ushahidi/platform#1470)

---
This change is [Reviewable](https://reviewable.io/reviews/ushahidi/platform-client/412)

### CODE REVIEW

**Comment by rjmackay** [comment]
Changes are so minor this can go straight to QA. @jshorland this should auto deploy to a branch deploy soon...

**Comment by jshorland** [comment]
i don't see any of this on qa.ushahididev.com -- is that where I'm supposed to be testing?

**Comment by rjmackay** [comment]
Argh. Sorry github drops the deployent link: http://qa.1470-create-survey-button.ushahidilab.com

**Comment by jshorland** [comment]
- successfully created and saved survey using create survey link under list of surveys
- successfully added all types of fields to survey
- successfully added two tasks with data fields to survey
- successfully deleted survey. 

PASSES QA

**Pull request merged**
