### PR TITLE
Remove plansndemo

### PR DESCRIPTION
**Pull request by Angamanga**
This pull request makes the following changes:
- Removes link to plans from settings-list
- Removes plans-page entirely
- Removes demo-bar

Testing checklist:
- [x] Go to settings
- [x] No plans-options should be available in the list
- [x] Try navigating to /settings/plan
- [x] You should not see the plans-page
- [x] Demo-bar is hard to test since it is removed and was hidden before. 

- [x] I certify that I ran my checklist

Fixes ushahidi/platform# .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by Angamanga** [comment]
@webong Could you review this one please?

**Comment by Angamanga** [comment]
@webong Reminding you to review this one!

**Comment by webong** [comment]
Oops ... I am just seeing this now. I'll give it a work through, so sorry for the delay.

**Comment by webong** [comment]
@Angamanga this looks good ... ready to go!

**Review by webong — APPROVED** [review]

**Comment by Angamanga** [comment]
@Obadha2 Ready for QA

**Comment by Obadha2** [comment]
QA'd, passes. 👍

**Pull request merged**
