### PR TITLE
4247 - Remove unused dependencies

### PR DESCRIPTION
**Pull request by Ifycode**
#### This pull request makes the following changes:
- Fixes issue ushahidi/platform#4247

#### Details (notes):
Removes unused dependencies in the code base/package.json. Check done with `npm-check`. Sometimes, npm-check lists used dependencies as unused because they can either only be found in the package.json and no where else, or because they are plugins only used in config files, or can't find a require or import statement for it. Confirmed whether a dependency is in use or not by using (vscode editor) search and/or going through the readme/docs of the dependencies. Found ten (10) dependencies unused after checking.

#### Removed 9/10 unused dependencies
* style-loader 
* raw-loader 
* phantomjs-prebuilt 
* node-libs-browser
* node-fetch 
* json-loader 
* fs-walk 
* socket.io-client 
* moment-timezone

#### Confirm that 1/10 dependency is unused before removing
* @uirouter/visualizer: Question - is this to be removed? Seeing that it's for visualizing states and also code for it wasn't removed but commented out in the app.js file as seen below. Not sure if I should remove this or not.
https://github.com/ushahidi/platform-client/blob/765b6148c8d0bd176b6d852515934387bf726e0e/app/app.js#L162

#### Testing checklist:
- [x] Check that unused dependencies have been removed
- [x] I certify that I ran my checklist

Fixes ushahidi/platform# .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by Angamanga** [comment]
@Ifycode Looks good! You can go ahead and remove the visualizer and the commented-out code as well 🎉.

**Comment by Ifycode** [comment]
Alright @Angamanga. Will remove it then.

**Comment by Ifycode** [comment]
I have removed the ui-router visualiser @Angamanga

**Review by Angamanga — APPROVED** [review]
🎉  Approved!

**Comment by Angamanga** [comment]
@Obadha2 This PR removes libraries that seem unused, so it shouldn't change anything, but it needs a smoke test to be double sure :)

**Pull request merged**
