### PR TITLE
adding notification-bar with warning if debug is switch on

### PR DESCRIPTION
**Pull request by Angamanga**
This pull request makes the following changes:
- Adds a notify-bar if debug-mode is switched-on in the backend

Testing checklist:
- [ ] Disable debug-mode in the backend (composer installdebug:disable)
- [ ] Reload client, a demo-bar should not appear
- [ ] Enable debug-mode in the backend (composer installdebug:enable)
- [ ] Reload client, a demo-bar should appear with a warning.

NOTE This only shows up at login + at reload if user already is logged in and the bar can be dismissed. Do we want to always show it?

- [x] I certify that I ran my checklist

Fixes ushahidi/platform# .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by tuxpiper** [comment]
I was thinking, maybe it would be better to show this only to logged in users (dare I even say, users of the admin group?) . Otherwise, it may just annoy most site visitors without really a point.

**Comment by Angamanga** [comment]
@tuxpiper Yep, that makes sense, added that now.

**Comment by rowasc** [comment]
@Angamanga @tuxpiper I think it's probably necessary to show it to non-logged in users, or many deployers won't notice it as they may not log in at all when they do the setup.

**Comment by tuxpiper** [comment]
> I think it's probably necessary to show it to non-logged in users, or many deployers won't notice it as they may not log in at all when they do the initial setup.

That also sounds reasonable to me 🤷‍♂  . Although in that case, I think it would be an improvement to change the wording, taking into consideration that not everyone that sees the banner may be able to take action on it.

> (that however is also a problem, because we need to make them login somehow to change their password!!)

:) maybe another check?

**Comment by rowasc** [comment]
>:) maybe another check?
Totally :)

**Comment by rowasc** [comment]
re extra login check, ideally what I would _like_ to see is a forced password change in the backend installation (ie after migration) + this warning which would only show up if you somehow manage to skip that password change . Creating a ticket for it since I'm still editing videos and don't want to forget ha :D

**Comment by Angamanga** [comment]
@rowasc @tuxpiper Updated to remove the admin-check + changed the language to make it clear its for admins.

**Comment by rowasc** [comment]
@Angamanga I think a few tests are failing, could you check ?

**Comment by rowasc** [comment]
Nice 🎉 . I think it can be merged since it passed the tests now :)

**Pull request merged**
