### PR TITLE
issue #4122 Show HDX logo

### PR DESCRIPTION
**Pull request by Sunairaa**
This pull request makes the following changes:
- fixed: [#4122](https://github.com/ushahidi/platform/issues/4122)
- Show the HDX logo on the configure HDX API screen.

**Problem**
HDX logo was not showing on the HDX Configure API screen.
image

**Bug observed**
locally and in .io

**Solution**

- Changes made in webpack.config.js
- Added `esModule: false` to the file-loader options which was true by default.
- Replace code `loader: 'url-loader?limit=10000'` with `loader: 'file-loader',options: {esModule: false,}`

image

image

Testing checklist:
- [x] login with my deployment credentials.

- [x] Go to settings > Configure HDX API

- [x] Show logo on top right corner.

- [x] I certify that I ran my checklist

Fixes ushahidi/platform[#4122](https://github.com/ushahidi/platform/issues/4122) .

Ping @ushahidi/platform

### CODE REVIEW

**Review by rowasc — APPROVED** [review]
@Sunairaa thanks! I tried with for the Share button PNGs , the HDX one, and also checked the map view to be safe that everything loads fine. 

@Angamanga While this means those PNG images are not in the bundle in base64, they aren't very many of them (PNGs) as far as I can tell so file-loader should be fine? we mainly use SVGs for icons . What do you think? pre-approving but you can reject if you disagree :)

**Comment by Sunairaa** [comment]
> @Sunairaa thanks! I tried with for the Share button PNGs , the HDX one, and also checked the map view to be safe that everything loads fine. 
> 
> @Angamanga While this means those PNG images are not in the bundle in base64, they aren't very many of them (PNGs) as far as I can tell so file-loader should be fine? we mainly use SVGs for icons . What do you think? pre-approving but you can reject if you disagree :) 

You're welcome @rowasc ..
Yeah I also noticed there are icons with svgs that worked fine because I only make changes for png everything else was working fine. If there is any change or suggestion you can notify me..
Thanks 🙂

**Comment by Sunairaa** [comment]
Hey @Angamanga @rowasc can you accept this PR as hactoberfest too I am also applying for hactoberfest this year!

**Review by rowasc — APPROVED** [review]
@Angamanga This looks good to me. Please reject if you disagree. Thanks.

**Comment by Angamanga** [comment]
@Sunairaa Looks good! Thank you for your contribution! 
@Obadha2 Ready for QA!

**Comment by Obadha2** [comment]
QA'd, passes. 👍

**Pull request merged**
