### PR TITLE
Added icons in settings view of platform-client

### PR DESCRIPTION
**Pull request by rohit645**
This pull request makes the following changes:
- [x] Adds Icons in the settings view of platform client. 
- [x] Below screenshots shows before and after changes.
- [x] Fixes ushahidi/platform#3856.

Testing checklist:
- [x] verified coding style using jscs
- [x] verified eslint checklist

Fixes ushahidi/platform#3856 .

**Changes**
*Before*

Screenshot from 2020-03-01 03-25-15

*After*

Screenshot from 2020-03-01 04-26-33

### CODE REVIEW

**Comment by rohit645** [comment]
@Angamanga @rowasc, I have added icons to the settings view. Are they okay?

**Comment by Erioldoesdesign** [comment]
Hi @rohit645 I know previously, the internal product and design team at Ushahidi talked about adding icons in this settings section (sorry, it's undocumented) but I would say that these currently don't fit within the wider design system/visuals of Ushahidi's iconography/navigation.

If @Angamanga and @rowasc agree I would be happy to mock-up and provide some guidance for this as I do think Icon's here would help with section recognition.

@rohit645 I think it's also worth having a look at this old closed ticket for CSS/Styling examples and some pixel ratios/sizes of icons:https://github.com/ushahidi/platform/issues/2648

**Comment by rohit645** [comment]
Hi @Erioldoesdesign, I was not aware of this. But I would be glad to work on it if I get mock-ups for this :)

**Comment by Angamanga** [comment]
@Erioldoesdesign If you have time to do a design for this it would be great! 💐 🎉

**Comment by Erioldoesdesign** [comment]
@Angamanga of course ❤️ we can take a look at some mocks on our next sync and I'll use #3856 to do async discussion on this.

**Comment by Angamanga** [comment]
Closing this since it is nothing we will do right now.

**Pull request closed without merging**
