### PR TITLE
ushahidi/platform#2086 make http://... resources scheme relative (//...)

### PR DESCRIPTION
**Pull request by tuxpiper**
Makes "http://" resources to be referenced using scheme relative URLs ("//")

### CODE REVIEW

**Comment by rowasc** [comment]
- [ ] //{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png
- [ ] lorempixel.com/400/300
https://www.gravatar.com/avatar/%7B%7B%20post.user.gravatar%20%7C%7C%20'00000000000000000000000000000000'%20%7D%7D?d=retro&s=40 
- Gravatar post metadata
- Gravatar post toolbox
- Gravatar post messages

**Comment by rowasc** [comment]
1. the html where lorempixel is doesn't look like its being used. 
2. there are 2 other places where gravatar is used, not relative (but https)
app/common/directives/mode-bar/mode-bar.html
and 
 app/settings/users/users.html.

**Comment by tuxpiper** [comment]
Rebasing to master for a hotfix . It looks like this could be breaking geolocation in chrome + iOS .

**Comment by tuxpiper** [comment]
Discarding in favour of #762 (hotfix)

**Pull request closed without merging**
